[tool.poetry]
name = "hallucinations"
version = "0.1.0"
description = ""
authors = ["Rodolfo Ferro <rodolfoferroperez@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
matplotlib = "^3.1"
numba = "^0.45.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
