[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "reading-helper"
description = ""
version = "0.1.7"
authors = ["Nathan Hunt <neighthan.hunt@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/neighthan/reading-helper"
include = ["pyproject.toml", "template.md"]

[tool.poetry.scripts]
make_paper_page = "reading_helper:scripts_api.make_paper_page"
search_tags = "reading_helper:scripts_api.search_tags"

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
pre-commit = "^1.14"
pytest = "^4.0"
pytest-cov = "^2.6"
twine = "^1.13"
invoke = {git = "https://github.com/neighthan/invoke.git"}
ipykernel = "^5.1"
