[tool.poetry]
name = "po_publish"
version = "0.1.0"
description = "wraps `poetry publish --build` with some logic for my personal needs"
authors = ["Philip Olson <philip.olson@pm.me>"]
license = "WTFNMFPL-1.0"
readme = "README.md"
repository = "https://github.com/olsonpm/py_publish"
include = [
  "po_publish/license.txt",
  "po_publish/top_level.txt"
]

[tool.poetry.scripts]
po-publish = "po_publish.script:main"


[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
