AWSTemplateFormatVersion: '2010-09-09'
Description: Self hosted dynamic DNS with Lambda and API Gateway


Parameters:
  LambdaFunctionCode:
    Type: String
    Description: Python code of Lambda function to reflect public IP

  # HostedZoneId:
  #   Type: String
  #   Description: Route53 hosted zone id of domain name

  # HostName:
  #   Type: String
  #   Description: Domain name in Route53 hosted zone to bind to IP


Resources:
  LambdaFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: 'Nimi-DynamicDNS-Route53'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            {% if hosted_zones %}
              - Effect: "Allow"
                Action:
                  - "route53:ChangeResourceRecordSets"
                  - "route53:ListResourceRecordSets"
                Resource: 
                {% for hosted_zone in hosted_zones %}
                  - "arn:aws:route53:::hostedzone/{{ hosted_zone }}"
                {% endfor %}
            {% endif %}
              - Effect: "Allow"
                Action:
                  - "route53:GetChange"
                Resource:
                  - "arn:aws:route53:::change/*"

  # LambdaFunctionKey:
  #   Type: "AWS::KMS::Key"
  #   Properties:
  #     Enabled: True
  #     KeyPolicy:
  #       Version: "2012-10-17"
  #       Id: "key-default-1"
  #       Statemen:
  #         - Sid: "Allow use of the key"
  #           Effect: "Allow"
  #           Principal:
  #             AWS: !GetAtt LambdaFunctionRole.Arn
  #           Action:
  #             - "kms:Decrypt"
  #           Resource: "*"

  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: 
        ZipFile: !Ref LambdaFunctionCode
      {% if env %}
      Environment:
        Variables:
        {% for key, value in env.items() %}
          {{ key }}: {{ value }}
        {% endfor %}
      {% endif %}
      Handler: index.lambda_handler
      # KmsKeyArn: !GetAtt LambdaFunctionKey.Arn
      Role: !GetAtt LambdaFunctionRole.Arn
      Runtime: python3.6

  LambdaProxy:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: DynamicDNS API
      Description: Public API for self hosted dynamic DNS

  LambdaProxyPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${LambdaProxy}/*/*

  # ProxyKey:
  #   Type: "AWS::ApiGateway::ApiKey"
  #   Properties:
  #     Name: DynamicDNS API Key
  #     Enabled: True
  
  ProxyResourceANY:
    Type: AWS::ApiGateway::Method
    Properties:
      # ApiKeyRequired: True
      RestApiId: !Ref LambdaProxy
      ResourceId: !GetAtt [LambdaProxy, RootResourceId]
      HttpMethod: ANY      
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations

  ProxyDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn: ProxyResourceANY
    Properties: 
      RestApiId: !Ref LambdaProxy
      Description: Dynamic DNS API deployment
      StageName: dyndns

  # ProxyUsagePlan:
  #   Type: "AWS::ApiGateway::UsagePlan"
  #   Properties:
  #     ApiStages:
  #       - ApiId: !Ref LambdaProxy
  #         Stage: dyndns

  # ProxyUsagePlanKey:
  #   Type: "AWS::ApiGateway::UsagePlanKey"
  #   Properties:
  #     KeyId: !Ref ProxyKey
  #     KeyType: API_KEY
  #     UsagePlanId: ProxyUsagePlan

Outputs:
  # ApiKeyId:
  #   Value: !Ref ProxyKey
  ApiUrl:
    Value: !Sub "https://${LambdaProxy}.execute-api.${AWS::Region}.amazonaws.com/dyndns"
  LambdaFunctionName:
    Value: !Ref LambdaFunction
