[tool.black]
line-length = 80

[tool.isort]
line_length = 80
indent = '    '
multi_line_output = 3
combine_as_imports = true
order_by_type = false
use_parentheses = true
include_trailing_comma = true
force_sort_within_sections = true

[tool.poetry]
name = "shinymdc"
version = "1.2.1"
description = "Tool to compile markdown files to tex/pdf using pandoc, latexmk"
readme = "README.md"
authors = ["Jayanth Koushik <jnkoushik@gmail.com>"]
license = "MIT"
repository = "https://github.com/jayanthkoushik/mdc"

packages = [{ include = "mdc" }]

classifiers=[
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
]

[tool.poetry.scripts]
mdc = "mdc.mdc:main"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pylint = "^2.3"
isort = "^4.3"
bumpversion = "^0.5.3"
pre-commit = "^1.16"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
