[tool.poetry]
name = "django-handyman"
version = "1.0.0-rc1"  # Needs to be the version matching tag
description = ""
authors = ["Giannis Katsini <giannis.katsini@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
codecov = "^2.0"

[tool.poetry.dev-dependencies]
django = "^2.2"
flake8 = "^3.7"
autopep8 = "^1.4"
coverage = "^4.5"
