# coding: utf-8

"""
    Golem unlimited low level hub API

    API description in Markdown.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gu_rest_api
from gu_rest_api.models.command import Command  # noqa: E501
from gu_rest_api.rest import ApiException


class TestCommand(unittest.TestCase):
    """Command unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommand(self):
        """Test Command"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gu_rest_api.models.command.Command()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
