
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-07T15:32:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b0bce70d5304fbe863e48658bfb8adbe7aade2a",
 "version": "0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
