
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-11T15:59:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc4652e97ea59a6f96763bb29fd9d835bf9dae66",
 "version": "1.0.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
