# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bridge
from bridge.models.category_all_of import CategoryAllOf  # noqa: E501
from bridge.rest import ApiException


class TestCategoryAllOf(unittest.TestCase):
    """CategoryAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategoryAllOf(self):
        """Test CategoryAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bridge.models.category_all_of.CategoryAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
