
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-06T00:32:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "71212b6f5a51e386f8a998f45240144203391ef3",
 "version": "v0.16a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
