analysis_data_widget_bg_pictures_folder: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/cicada_mw_bg_pictures/analysis_data
analysis_params_widget_bg_pictures_folder: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/cicada_mw_bg_pictures/analysis_params
dir_name: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/nwb_files
overview_widget_bg_pictures_folder: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/cicada_mw_bg_pictures/overview
sessions_widget_bg_pictures_folder: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/cicada_mw_bg_pictures/sessions
tree_widget_bg_pictures_folder: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/cicada_mw_bg_pictures/tree
yaml_analysis_args_dir_name: /Users/pappyhammer/Documents/academique/these_inmed/robin_michel_data/data/yaml_cicada_args
