# Generated by Django 2.2.3 on 2019-09-10 20:45

from django.db import migrations, models
import django.db.models.deletion
import edc_model.validators.date


class Migration(migrations.Migration):

    dependencies = [("meta_lists", "0001_initial"), ("meta_prn", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="historicalendofstudy",
            name="offschedule_reason",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="meta_lists.OffstudyReasons",
                verbose_name="Reason patient was terminated from the study",
            ),
        ),
        migrations.AlterField(
            model_name="endofstudy",
            name="offschedule_datetime",
            field=models.DateTimeField(
                null=True,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Date patient was terminated from the study",
            ),
        ),
        migrations.RemoveField(model_name="endofstudy", name="offschedule_reason"),
        migrations.AddField(
            model_name="endofstudy",
            name="offschedule_reason",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="meta_lists.OffstudyReasons",
                verbose_name="Reason patient was terminated from the study",
            ),
        ),
        migrations.AlterField(
            model_name="historicalendofstudy",
            name="offschedule_datetime",
            field=models.DateTimeField(
                null=True,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Date patient was terminated from the study",
            ),
        ),
    ]
