[build-system]
requires = ['flit>=1.3']
build-backend = 'flit.buildapi'

[tool.flit.metadata]
module = 'scanpydoc'
author = 'Philipp Angerer'
author-email = 'phil.angerer@gmail.com'
home-page = 'https://github.com/theislab/scanpydoc/'
urls = { Documentation = 'https://icb-scanpydoc.readthedocs-hosted.com/' }
description-file = 'README.rst'
classifiers = [
    'Intended Audience :: Developers',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Programming Language :: Python :: 3',
    'Topic :: Documentation :: Sphinx',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Framework :: Sphinx :: Extension',
]
requires-python = '>=3.6'
requires = [
    'sphinx>=1.8',
    'get_version',
]

[tool.flit.metadata.requires-extra]
test = [
    'pytest',
    'pytest-cov',
    'pytest-black',
    'scipy',  # to test overrides
]
doc = [
    'sphinx-autodoc-typehints>=1.8',
]

[tool.black]
target-version = ['py36']

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36,py37
skipsdist = True

[testenv]
deps =
    flit
    future-fstrings
commands =
    flit install
    pytest
"""
