# coding: utf-8

"""
    Budgea API Documentation

    see https://www.budget-insight.com/budgea-api  # noqa: E501

    OpenAPI spec version: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import budgea
from budgea.api.recipients_api import RecipientsApi  # noqa: E501
from budgea.rest import ApiException


class TestRecipientsApi(unittest.TestCase):
    """RecipientsApi unit test stubs"""

    def setUp(self):
        self.api = budgea.api.recipients_api.RecipientsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_id_user_accounts_id_account_recipients_post(self):
        """Test case for users_id_user_accounts_id_account_recipients_post

        Add a recipient.  # noqa: E501
        """
        pass

    def test_users_id_user_connections_id_connection_accounts_id_account_recipients_post(self):
        """Test case for users_id_user_connections_id_connection_accounts_id_account_recipients_post

        Add a recipient.  # noqa: E501
        """
        pass

    def test_users_id_user_connections_id_connection_recipients_post(self):
        """Test case for users_id_user_connections_id_connection_recipients_post

        Add a recipient.  # noqa: E501
        """
        pass

    def test_users_id_user_recipients_post(self):
        """Test case for users_id_user_recipients_post

        Add a recipient.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
