# Generated by Django 2.2.3 on 2019-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("meta_ae", "0001_initial")]

    operations = [
        migrations.AlterModelManagers(name="aeinitial", managers=[]),
        migrations.RemoveField(model_name="aeinitial", name="ae_classification_old"),
        migrations.RemoveField(model_name="aeinitial", name="sae_reason_old"),
        migrations.RemoveField(
            model_name="historicalaeinitial", name="ae_classification_old"
        ),
        migrations.RemoveField(model_name="historicalaeinitial", name="sae_reason_old"),
        migrations.AddField(
            model_name="aeinitial",
            name="tmg_report_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 24 hours",
                null=True,
                verbose_name="Date and time AE reported to TMG",
            ),
        ),
        migrations.AddField(
            model_name="historicalaeinitial",
            name="tmg_report_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="AEs ≥ Grade 4 or SAE must be reported to the Trial Management Group (TMG) within 24 hours",
                null=True,
                verbose_name="Date and time AE reported to TMG",
            ),
        ),
    ]
