
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-13T14:06:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9b6857661a0843a1bfc1504027c0606cc83f6f3",
 "version": "v0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
