
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-06T11:08:15-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9d39dca09bad1e73c90c7fff278d8f0181963f2",
 "version": "1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
