[build-system]
requires = ['flit']
build-backend = 'flit.buildapi'

[tool.flit.metadata]
module = 'scvelo'
author = 'Volker Bergen'
author-email = 'volker.bergen@helmholtz-muenchen.de'
home-page = 'https://github.com/theislab/scvelo'
license = 'BSD'
description-file = 'README.rst'
requires-python = '>=3.6'
requires = ['scanpy>=1.3.3', 'anndata>=0.6.18', 'numpy>=1.14', 'pandas>=0.23.0', 'matplotlib>=2.2', 'umap-learn>=0.3.0',
            'loompy>=2.0.12', 'scipy>=1.0', 'scikit-learn>=0.19.1, != 0.21.0, != 0.21.1', 'joblib', 'setuptools']
requires-extra = { doc = ['docutils'], test = ['pytest', 'loompy'] }
keywords = 'RNAseq singlecell stochastic velocity transcriptomics'
classifiers = [
	'License :: OSI Approved :: BSD License',
	'Development Status :: 5 - Production/Stable',
	'Intended Audience :: Science/Research',
	'Natural Language :: English',
	'Programming Language :: Python :: 3',
	'Programming Language :: Python :: 3.6',
	'Programming Language :: Python :: 3.7',
	'Topic :: Scientific/Engineering :: Bio-Informatics',
	'Topic :: Scientific/Engineering :: Visualization',
]
