language: python
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
addons:
  firefox: latest-esr
before_install:
  # install geckdriver for firefox
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzvf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install tox-travis
script: tox
after_success:
- coveralls
deploy:
  provider: pypi
  skip_existing: true
  user: mshriver
  distributions: sdist bdist_wheel
  password:
    secure: Ej6jGl0SUJwbVd+8q1TyQA042uDidZMG0QQyCELe3KjrOWBie2pIdpiF4EGfmpzgiHQADZ/EDK4PnNFeRgJD2bYU8BEOzv70xsG9BrMDXNFsKnLdNkwP7h/4Pp2m917eT8fK7sdUpyEz+QaHX3+VAbFPKzcGf11MKqBZ5ztEzDaZrEFfy7xjCNFJgYNiYOmTGTQ3NhCRrTOCZ7gd20lWQPceZ7ApHW7VKobl4X4jbV2GuSWxBax9ai1pu27aRJkG3aIUdh2W7xaLdtvPRrESQ+YSiY4tQe4gTlnUHij7TPL0U8lT46NUa38589uDEsKkTKu9dBJtfNhbS0to7QSmL39pgS8f762H+JFvIOADlFbOoPSiQzmOvbmrYlvIBkQOCJ5i2/lAm37z9AiOHf5T36VkWoPyKzFxJUFCVUQSew4RZ0avnTfS2Pgy+lYU3440J/VgOgMT16AaHNAKIDigw2QbwZ8bO2FGExmP+yK5VSmehybdXoHlfrkQiiuJVQlwN6CDzgMXR8H1/7ZNhxdGGVSp1pjSAdSddUGSkxUDXTRfo84mQBxOmL6rQGvRjNgAnLXocQ2M5nYY4q0CHv+h2jRQRatHjdzs9nsqWhb0zHDiGIT7yfZguU3iOIjXMZTIHCZILpZh4b+bQ08v/3cnOPCDYvVwrIcjpTONHqUOH7k=
  on:
    tags: true
    repo: RedHatQE/widgetastic.patternfly
