
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-22T12:21:45+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bb184487149317ee4c47e0e81e30748f03fa9c9",
 "version": "0.16.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
