[project]
name = "orjson"
repository = "https://github.com/ijl/orjson"

[build-system]
build-backend = "maturin"
requires = ["maturin>=0.7.2,<0.8"]

[tool.maturin]
manylinux = "off"
rustc-extra-args = "-C target-feature=+sse2"
strip = "on"
