[tool.poetry]
name = "simple_test_default_reporter"
version = "0.3.0"
description = "The default reporter for simple_test"
authors = ["Philip Olson <philip.olson@pm.me>"]
license = "WTFNMFPL-1.0"
readme = "README.md"
repository = "https://github.com/olsonpm/py_simple-test-default-reporter"
include = [
  "simple_test_default_reporter/license.txt",
  "simple_test_default_reporter/top_level.txt",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pretty_simple_namespace = "^0.1.0"
toml = "^0.10.0"
is_git_repo_clean = "^0.3.4"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
simple_chalk = "^0.1.0"

[tool.vendorize]
target = "simple_test_default_reporter/_vendor"
packages = [
  "ordered_set >=3.1,<3.2",
  "simple_chalk >=0.1.0,<0.2",
  "tedent >=0.1.5,<0.2",
  "wrapt >=1.10,<1.11",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
