[tool.poetry]
name = "loggable-jdv"
version = "0.1.4"
description = "Logging package. Alpha. Not meant for wider release."
authors = ["jvrana <justin.vrana@gmail.com>"]
packages = [
    { include = "loggable", from = "." },
]

[tool.poetry.dependencies]
python = "^3.5"
colorlog = "^4.0"
tqdm = "^4.32"
arrow = "^0.14.3"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true, python = "^3.6"}
pytest = "^5.0"
tox = "^3.13"
tox-conda = "^0.2.0"
keats = "^0.2.26"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
