# Generated by Django 2.2.4 on 2019-08-22 12:32

from django.db import migrations, models
import oms_cms.backend.languages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пример: Русский', max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Пример: ru', max_length=5, unique=True, verbose_name='Сокращение названия')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='AbstractLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.ForeignKey(on_delete=models.SET(oms_cms.backend.languages.models.get_sentinel_lang), to='languages.Lang', verbose_name='Язык')),
            ],
        ),
    ]
