
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-15T19:25:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5852068d7fee5a414f70ac1eecca3e463fe037c",
 "version": "1.0.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
