
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-20T20:09:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd196b04cc04addf04bbccf7381f62503437eea2",
 "version": "v0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
