
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-20T17:21:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f7bad937045c8b77583b1fb377db91d0a7cabf3",
 "version": "0.0.56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
