
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-21T11:30:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "546edf4d7dffb49e9e26e55546a6f0b314e1a22c",
 "version": "0.6.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
