# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-17 11:09
from __future__ import unicode_literals

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_profile', '0002_auto_20190913_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='urlid',
            field=djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True),
        ),
    ]
