language: python
python:
  - "3.6"
dist: bionic
env:
  global:
  - TWINE_USERNAME="anthrotype"
  - secure: Wq6SwEAQVkWo7CgTNBFUYbYbN9GkEA8TcuJi7rdugruRHu5dvv2fHOCMzgG33xYDlBCJbb3KuAviLylpeNtDe+M34mcki3G2R9ovOxx9g2l213wklzGRfdovHAHo8kujRLPNWz/Qk5f8gkLXv6HrZGFZ37UTx9EKYJ6/K0oHPhJ2jlKLp/mJT/pxjauLewJvrcCRCg4hbJXTMY1Skk3ebpxAHv+7MqtWxeCgAtNUvL8LH4euCD6ZtqgAZY2kWaBfB0yQPbQiTvPgaq+N3YMOsq/FibtWrZC10CUcOFM0zLL6HyNKDIWkYxZ7vfFAOIB5lMD2Mul6MNBP4u6Im5wwg1tNQ+GaK/a7clXmuZ7y8QyxtEXHi7KaEYt4s1ZB1y79cctnpRY1j+NNoYrooyfCsy9ND7Gbw/zKHxmhIjZcmUd2JQqq2azkOZeFzYyyued+ZmOyF5+KrlOy418/yCQA4n27qclewjh3GpoEM9zogZAYcbtJGtEpiRCKCrYiDaIl81HwVvfgHShF3f8EY+AlASuor7yY+4NSVG0oVg3VXrbf7cLJ+NKPv5Hadu4URl7oPApMujC0svA83qiqzfbyxiQJiyAPp2rXTWtP5JSmV/+znlFFSyQ2Bm877YA/hdFk4UviZ+cBD2nx3tUFJvHRqGroypMX/uR1BI52s+u9ia0=
services:
  # We run "headless" tests with xvfb (X Virtual Framebuffer)
  - xvfb
addons:
  apt:
    packages:
      - libxkbcommon-x11-0  # To make Qt load for tests

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

# The following prevents Travis from running CI on pull requests that come from a
# branch in the same repository. Without this, it will run the same CI for the
# pull request branch _and_ the pull request itself, which makes no sense.
branches:
  only:
    - master
    # We want to build version tags as well.
    - /^\d+\.\d+.*$/

before_install:
  # Check environment
  - echo $PATH
  - which python3
  - python3 --version
  # Install requirements
  - pip3 install --upgrade setuptools wheel
  - pip3 install --upgrade -r dev-requirements.txt -r requirements.txt
  # Print PyQt5 and SIP versions
  - python -c "import PyQt5.sip as sip; print(sip.__file__); print('sip version:', sip.SIP_VERSION_STR)"
  - python -c "from PyQt5 import Qt; print(Qt.__file__); print('PyQt5 version:', Qt.PYQT_VERSION_STR)"

install:
  - pip3 install .

script:
  - pre-commit run -a
  - pytest

# deploy sdist and wheel packages to PyPI on tags
after_success:
- |
  if [[ $TRAVIS_TAG && $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
    python -m pip install --upgrade pip setuptools setuptools_scm wheel twine
    git fetch --unshallow
    python setup.py sdist bdist_wheel
    python -m twine upload dist/*.zip dist/*.whl
  fi

deploy:
  # also create a Github Release with the current tag
  - provider: releases
    api_key:
      secure: A/a0IpTz1lCcrASVwriV0iLBNe8Q2gMQYOPS+8QHjS9O1R/hCL42CNc5h10zHN1zPrl19Rkocm4bEQIm1ExFqCF384dSv13LOlELX62fnDy8+rGRh7LysCPCEpk9PCngt8H4rtCXPJPE4P3guVfLLjWOCbT3vFm2IgwOTSOKARSfx2y4Akfas8w42zDqzsXCw1eMD0yGs6PIeqsJfEx3BBHjNvs7ikV6dZMAO1OaakQDdKIyPzQXiHAzJ0U5CZL46oVlXIHeqsO3yFXH/sxFNH1uPbK7stZy0Q/6WHB9a0dnDwR2QFMa8jaaAJItgeC3ppoWq4rMaybamvWUREzcI3XRLGuJwYWRZNTVjMKjasgmY0scWmtEwFsZxr9IBRjftq1jsBwp1pPW2NwE0uFmhkJJDua7fZ9qpnzvG+BVN7+u4+GtAu1l7SWWYde8WAXC3IKYY7kpgu14STAAGlOguvR/s1d1yx2vrj4jZoALsQRGjuhPv9twW6b1RPmHFupuiX2a3qbd3cm/LuTbSC9nPQn0NPdQ5kx6xodoEpZgh7IDcrIMG7tzG0VxtYiwTlJZVbAMBdTMojmZyRTq4+timVwsKMkBZid1ITbvimUnO6ycV77GYXPNoZQWkeKgtsR4VBPdDyI2/e9trrqAYqDIb+5zEpkJMBCc6wZZbYcmZo8=
    on:
      repo: trufont/trufont
      tags: true
      all_branches: true
      python: 3.6
