# coding: utf-8

"""
    Budgea API Documentation

    see https://www.budget-insight.com/budgea-api  # noqa: E501

    OpenAPI spec version: 2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ConnectorLogo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'id_connector': 'int',
        'id_file': 'int',
        'type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'id_connector': 'id_connector',
        'id_file': 'id_file',
        'type': 'type'
    }

    def __init__(self, id=None, id_connector=None, id_file=None, type=None):  # noqa: E501
        """ConnectorLogo - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._id_connector = None
        self._id_file = None
        self._type = None
        self.discriminator = None

        self.id = id
        self.id_connector = id_connector
        self.id_file = id_file
        if type is not None:
            self.type = type

    @property
    def id(self):
        """Gets the id of this ConnectorLogo.  # noqa: E501


        :return: The id of this ConnectorLogo.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConnectorLogo.


        :param id: The id of this ConnectorLogo.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def id_connector(self):
        """Gets the id_connector of this ConnectorLogo.  # noqa: E501

        ID of the connector  # noqa: E501

        :return: The id_connector of this ConnectorLogo.  # noqa: E501
        :rtype: int
        """
        return self._id_connector

    @id_connector.setter
    def id_connector(self, id_connector):
        """Sets the id_connector of this ConnectorLogo.

        ID of the connector  # noqa: E501

        :param id_connector: The id_connector of this ConnectorLogo.  # noqa: E501
        :type: int
        """
        if id_connector is None:
            raise ValueError("Invalid value for `id_connector`, must not be `None`")  # noqa: E501

        self._id_connector = id_connector

    @property
    def id_file(self):
        """Gets the id_file of this ConnectorLogo.  # noqa: E501

        Id of the Bank/Provider Logo  # noqa: E501

        :return: The id_file of this ConnectorLogo.  # noqa: E501
        :rtype: int
        """
        return self._id_file

    @id_file.setter
    def id_file(self, id_file):
        """Sets the id_file of this ConnectorLogo.

        Id of the Bank/Provider Logo  # noqa: E501

        :param id_file: The id_file of this ConnectorLogo.  # noqa: E501
        :type: int
        """
        if id_file is None:
            raise ValueError("Invalid value for `id_file`, must not be `None`")  # noqa: E501

        self._id_file = id_file

    @property
    def type(self):
        """Gets the type of this ConnectorLogo.  # noqa: E501

        Logo's type  # noqa: E501

        :return: The type of this ConnectorLogo.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ConnectorLogo.

        Logo's type  # noqa: E501

        :param type: The type of this ConnectorLogo.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectorLogo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
