
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "branch": "rc/maintenance",
 "dirty": false,
 "error": null,
 "full-revisionid": "a70a45f062687beb510fb3192e4227754e1dff39",
 "version": "1.3.12rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
