# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63ommon.proto\"f\n\x0b\x43lientQuery\x12\x17\n\x0f\x44\x65vicevendorurl\x18\x01 \x01(\t\x12\x12\n\nDevicetype\x18\x02 \x01(\t\x12\x17\n\x0f\x44\x65vicefeatureid\x18\x03 \x01(\t\x12\x11\n\tArugments\x18\x04 \x01(\x0c\"\xfe\x01\n\x08Response\x12#\n\x05\x45rror\x18\x01 \x01(\x0e\x32\x14.Response.ResultType\x12\x0e\n\x06Result\x18\x02 \x01(\x0c\"\xbc\x01\n\nResultType\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x19\n\x15NO_ERROR_WITH_PROMISE\x10\x01\x12\x16\n\x12RESOURCE_NOT_FOUND\x10\x02\x12\x12\n\x0e\x41RGUMENT_ERROR\x10\x03\x12\x0f\n\x0bSTATE_ERROR\x10\x04\x12\x19\n\x15INTERNAL_SERVER_ERROR\x10\x05\x12\x12\n\x0eNOT_AUTHORIZED\x10\x06\x12\x19\n\x15SERVICE_NOT_AVAILABLE\x10\x07\x62\x06proto3')
)



_RESPONSE_RESULTTYPE = _descriptor.EnumDescriptor(
  name='ResultType',
  full_name='Response.ResultType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR_WITH_PROMISE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESOURCE_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARGUMENT_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_ERROR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_SERVER_ERROR', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_AUTHORIZED', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_NOT_AVAILABLE', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=187,
  serialized_end=375,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_RESULTTYPE)


_CLIENTQUERY = _descriptor.Descriptor(
  name='ClientQuery',
  full_name='ClientQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Devicevendorurl', full_name='ClientQuery.Devicevendorurl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Devicetype', full_name='ClientQuery.Devicetype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Devicefeatureid', full_name='ClientQuery.Devicefeatureid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Arugments', full_name='ClientQuery.Arugments', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=118,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Error', full_name='Response.Error', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Result', full_name='Response.Result', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_RESULTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=375,
)

_RESPONSE.fields_by_name['Error'].enum_type = _RESPONSE_RESULTTYPE
_RESPONSE_RESULTTYPE.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['ClientQuery'] = _CLIENTQUERY
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientQuery = _reflection.GeneratedProtocolMessageType('ClientQuery', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTQUERY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:ClientQuery)
  })
_sym_db.RegisterMessage(ClientQuery)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
