
[tool.black]
line-length=79

[tool.poetry]
name = "pyuubin"
version = "0.1.1"
description = "Mailing services with HTTP Api"
authors = ["Michal Mazurek <mazurek.michal@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/MichalMazurek/pyuubin.git"
homepage = "https://pyuubin.io"
documentation = "https://pyuubin.io"
readme = "./README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: Free To Use But Restricted",
    "Programming Language :: Python :: 3.7",
    "Topic :: Communications :: Email"
]
packages = [
    {include = "pyuubin"}
]

[tool.poetry.dependencies]
python = "^3.7"
jinja2 = "^2.10"
aiosmtplib = "^1.0"
click = "^7.0"
aioredis = "^1.2"
msgpack = "^0.6.1"
html2text = "^2018.1"
trio = "^0.11.0"
envparse = "^0.2.0"
bcrypt = "^3.1"
tblib = "^1.3"
coloredlogs = "^10.0"
hypercorn = "^0.6.0"
pydantic = "^0.32.2"
fastapi = "^0.38.1"
python-dotenv = "^0.10.3"
email-validator = "^1.0"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.10.0"
pytest = "^4.2"
pytest-cov = "^2.6"
asynctest = "^0.12.2"
hypothesis = "^4.5"
requests = "^2.22"
pylama = "^7.7"
eradicate = "^1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

