# Generated by Django 2.2.4 on 2019-08-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190829_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
    ]
