[tool.poetry]
name = "jobstack"
version = "0.1.1"
description = "Commandline utility for organizing and scheduling project tasks across a team."
authors = ["Mark Gemmill <mark@markgemmill.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
]
include = [
    "src/jobstack/*.html",
    "src/jobstack/*.css",
    "src/jobstack/*.js"
]

[tool.poetry.scripts]
jobstack = 'jobstack:app.main'

[tool.poetry.dependencies]
python = "^3.7"
pendulum = "^2.0"
jinja2 = "^2.10"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
ipython = "^7.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
