
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-16T06:59:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "83b2a0538f7b9cbfaa38b7d64f81ca8188432b12",
 "version": "v0.6.a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
