# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'tsv'), (1, 'csv'), (2, 'txt'), (3, 'json'), (4, 'html'), (5, 'fastq'), (6, 'bam'), (7, 'cram'), (8, 'gvcf'), (9, 'vcf'), (10, 'report'), (11, 'bed'), (12, 'bigwig'), (13, 'wigfix'), (14, 'chromatograms'), (15, 'other')]),
        ),
    ]
