dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: YuVU1r8L2bgMcgL34DibaudiCVZANqt21sapSiNJH/o3GNXEqUy91jworFdV3B+UAws4goRikjsCtZDSkPvj7eXtEk7+skyOAzXH/iLSvXPgcuHU63FZwfYy0l0CSVoAUrjtCpkK13MvPDfQThnuu58n+Kt248RaVlUSQxoV+3OSw8ssjRPr2zb2ooVi/SqBwHsem7PHWBiYTgQyeJEpEXEoppI+Q5Fn0H5U9N3Q3yP8HpCLdCRwMpnXLNuW06ALwWkAus5Y204r55hyK/i0pHEJURNkdsQEAbbnwNc8MfWWlcvvACMhuon01ucOdwyLT9EbslyhnKQrgy/oqMOPTwIPzFIVeNSbvxZgHAVhjCEQlSnvL2+LWZioT07/pRhE4/DAtQQGbv2TEt1X6McqviDX795pLObO90q0+wHwSUHDpeoi/oiI1znUvzO/cWxOKc/CRWNSJt/9Vh8zRmU4SqliHz1SHTifei1n0e4t77vQBpDdWCJJL2u2JkF92hPVjQywGL/N8LB1/RlVEEJVolpIARI8nyvw6GsmQLfe9BsW5PDa/9oKhhXlTicUEsKgnE5vJcf95jGM5Lp+37+FD4vHdZS2ssXL+QwbFOu/9br0+ZJS+f1qNtSKOXBqkuejWhrinTCVMuqkL/D84/kUxwLlKgmm2u94AURj7H8OzKI=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_max31865.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-max31865 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
