# Generated by Django 2.2.5 on 2019-09-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('microsoft_auth', '0003_microsoft_id_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_enabled', models.BooleanField(default=True)),
                ('login_type', models.CharField(choices=[('ma', 'Microsoft Account'), ('xbl', 'Xbox Live Account')], max_length=2)),
                ('tenant_id', models.CharField(default='common', max_length=80)),
                ('client_id', models.CharField(blank=True, default='', max_length=80)),
                ('client_secret', models.CharField(blank=True, default='', max_length=80)),
                ('extra_scopes', models.CharField(blank=True, default='', max_length=80)),
                ('auto_create', models.BooleanField(default=True)),
                ('register_inactive_admin', models.BooleanField(default=False)),
                ('xbl_sync_username', models.BooleanField(default=False)),
                ('auto_replace_accounts', models.BooleanField(default=False)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
