# coding: utf-8

"""
    Budgea API Documentation

    see https://www.budget-insight.com/budgea-api  # noqa: E501

    OpenAPI spec version: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import budgea
from budgea.api.administration_api import AdministrationApi  # noqa: E501
from budgea.rest import ApiException


class TestAdministrationApi(unittest.TestCase):
    """AdministrationApi unit test stubs"""

    def setUp(self):
        self.api = budgea.api.administration_api.AdministrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clients_get(self):
        """Test case for clients_get

        List clients  # noqa: E501
        """
        pass

    def test_clients_id_client_delete(self):
        """Test case for clients_id_client_delete

        Delete a client  # noqa: E501
        """
        pass

    def test_clients_id_client_get(self):
        """Test case for clients_id_client_get

        Get information about a client  # noqa: E501
        """
        pass

    def test_clients_id_client_logo_delete(self):
        """Test case for clients_id_client_logo_delete

        Delete the client logo  # noqa: E501
        """
        pass

    def test_clients_id_client_logo_post(self):
        """Test case for clients_id_client_logo_post

        Update the client logo  # noqa: E501
        """
        pass

    def test_clients_id_client_put(self):
        """Test case for clients_id_client_put

        Update a client  # noqa: E501
        """
        pass

    def test_clients_post(self):
        """Test case for clients_post

        Create a client  # noqa: E501
        """
        pass

    def test_config_get(self):
        """Test case for config_get

        Get configuration of the API.  # noqa: E501
        """
        pass

    def test_config_logs_get(self):
        """Test case for config_logs_get

        Get configuration change history of the API.  # noqa: E501
        """
        pass

    def test_config_post(self):
        """Test case for config_post

        Set a configuration value on the API.  # noqa: E501
        """
        pass

    def test_merchants_get(self):
        """Test case for merchants_get

        List clients  # noqa: E501
        """
        pass

    def test_merchants_id_client_logo_delete(self):
        """Test case for merchants_id_client_logo_delete

        Delete the client logo  # noqa: E501
        """
        pass

    def test_merchants_id_client_logo_post(self):
        """Test case for merchants_id_client_logo_post

        Update the client logo  # noqa: E501
        """
        pass

    def test_merchants_post(self):
        """Test case for merchants_post

        Create a merchant. Needs a user identified in bearer to be used  # noqa: E501
        """
        pass

    def test_monitoring_get(self):
        """Test case for monitoring_get

        get performances stats on this instance  # noqa: E501
        """
        pass

    def test_test_sync_post(self):
        """Test case for test_sync_post

        Test synchronization on a random connection.  # noqa: E501
        """
        pass

    def test_test_webhooks_post(self):
        """Test case for test_webhooks_post

        Test synchronization on a random connection.  # noqa: E501
        """
        pass

    def test_webhooks_auth_delete(self):
        """Test case for webhooks_auth_delete

        Deletes all webhook authentication types  # noqa: E501
        """
        pass

    def test_webhooks_auth_get(self):
        """Test case for webhooks_auth_get

        Get webhooks authentication types  # noqa: E501
        """
        pass

    def test_webhooks_auth_id_auth_delete(self):
        """Test case for webhooks_auth_id_auth_delete

        Deletes the webhook authentication type  # noqa: E501
        """
        pass

    def test_webhooks_auth_id_auth_post(self):
        """Test case for webhooks_auth_id_auth_post

        Updates the webhook authentication type  # noqa: E501
        """
        pass

    def test_webhooks_auth_id_auth_put(self):
        """Test case for webhooks_auth_id_auth_put

        Updates the webhook authentication type  # noqa: E501
        """
        pass

    def test_webhooks_auth_post(self):
        """Test case for webhooks_auth_post

        Adds a new webhook authentication type  # noqa: E501
        """
        pass

    def test_webhooks_delete(self):
        """Test case for webhooks_delete

        Deletes all webhooks  # noqa: E501
        """
        pass

    def test_webhooks_get(self):
        """Test case for webhooks_get

        Get webhooks  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_add_to_data_delete(self):
        """Test case for webhooks_id_webhook_add_to_data_delete

        delete all entries  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_add_to_data_get(self):
        """Test case for webhooks_id_webhook_add_to_data_get

        retrieve the list of the value to add in webhooks when sending the requested webhook  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_add_to_data_key_delete(self):
        """Test case for webhooks_id_webhook_add_to_data_key_delete

        delete the requested entry  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_add_to_data_key_get(self):
        """Test case for webhooks_id_webhook_add_to_data_key_get

        retrieve the value to add in the requested webhook for the requested name  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_add_to_data_key_post(self):
        """Test case for webhooks_id_webhook_add_to_data_key_post

        upate the requested field to store in user config when calling the endpoint  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_add_to_data_post(self):
        """Test case for webhooks_id_webhook_add_to_data_post

        Setup a field to store in user config when calling the endpoint  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_delete(self):
        """Test case for webhooks_id_webhook_delete

        Deletes a webhook  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_logs_get(self):
        """Test case for webhooks_id_webhook_logs_get

        Get webhooks logs.  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_post(self):
        """Test case for webhooks_id_webhook_post

        Updates a webhook  # noqa: E501
        """
        pass

    def test_webhooks_id_webhook_put(self):
        """Test case for webhooks_id_webhook_put

        Updates a webhook  # noqa: E501
        """
        pass

    def test_webhooks_post(self):
        """Test case for webhooks_post

        Adds a new webhook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
