# coding: utf-8

"""
    Budgea API Documentation

    see https://www.budget-insight.com/budgea-api  # noqa: E501

    OpenAPI spec version: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import budgea
from budgea.models.inline_response20019 import InlineResponse20019  # noqa: E501
from budgea.rest import ApiException


class TestInlineResponse20019(unittest.TestCase):
    """InlineResponse20019 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20019(self):
        """Test InlineResponse20019"""
        # FIXME: construct object with mandatory attributes with example values
        # model = budgea.models.inline_response20019.InlineResponse20019()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
