[tool.poetry]
name = "envtoml"
version = "0.1.1"
description = "A simple way of using environment variables in TOML configs (via interpolation)"
authors = ["mr.Shu <mr@shu.io>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/mrshu/envtoml"
keywords = ['TOML', 'environment', 'variables', 'config']
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
nose = "^1.3"
coverage = "^4.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
