language: python

python:
  - 2.7

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py -c travis.cfg
  - bin/buildout -N -c travis.cfg annotate
  - bin/buildout -Nc travis.cfg
  - travis_wait 30 mvn install

script:
  - bin/code-analysis
  - bin/test

after_success:
  - bin/createcoverage
  - pip install --upgrade pip
  - pip install -q coveralls==0.5
  - coveralls

notifications:
  email:
    recipients:
      - devs@imio.be
      - travis-ci@ecreall.com
    on_success: change
    on_failure: change
