<<: &shared
  language_name: SENĆOŦEN
mappings:
  - display_name: SENĆOŦEN to IPA
    mapping: str_to_ipa.json
    in_lang: str-sen
    out_lang: str-sen-ipa
    as_is: true
    authors:
      - Aidan Pine
    <<: *shared
  - display_name: SENĆOŦEN IPA to English IPA
    mapping: str-sen-ipa_to_eng-ipa.json
    in_lang: str-sen-ipa
    out_lang: eng-ipa
    as_is: false
    authors:
      - Aidan Pine
    <<: *shared