[tool.poetry]
name = "gerby"
version = "0.3.0"
description = "Core functionality for Very data analysis."
authors = ["Jeff McGehee <jeff@verypossible.com>", "Bill Brock <bill@verypossbile.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0.25.0"
numpy = "^1.17"
requests = "^2.22"
cached_property = "^1.5"
slackclient = "1.3.2"

[tool.poetry.dev-dependencies]
black = { version = "*", allows-prereleases = true }
isort = "^4.3"
ipython = "^7.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
