# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: xenial
language: python
python:
  - "3.6"

cache:
  pip: true

env:
  - DEPLOY_PYPI="true"

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  - provider: pypi
    user: adafruit-travis
    password:
      secure: "p4KRS1VtWMuhJ9Xs+P93X1VZoCa9ZhFSpmPkSW4RmpWRiytDytaaqin78tcsBBaU8SiFILwupB8faol1vhNFfFVa/q4JM8AQ0rUL35XLFXXeIizUrTq/NJnQyX1sqe9ry+sDNi3cgpqj+XHdBJYSkcmL/hI51Uaf2h/9ihiw9vVQJKpUfrDDqym0JLtfYMFVTnKHIc6gNQaRn3KsLClrr2znl1gTM1Y9XSaGhoKzob/RpXMZ7nB1nrp/Q+hRvAcMTwV5TxN5awiXMaBcJILlACPvNR+oprxBLV+++u4Pp6AO8fj/zi+vQ95ZyINBWNu0qFLTRysMjkP/QWNP+CY1WZjtHDUdn9EedphIRgzH3GG4IpA05X0QPiSNKqnvWGC3Y+rHyaRn/jvw7IziBjFmuqZZYEboUJbZThuZOo7I9gpzDJ0RjjKIk0sWyMMt0K+LWZXpW4DBa1yq3bSqSCeHA7OBh2HeX8ESh13pVeeFjQkySZbcSbn2G4NHjg0VJ3xokQNxOgjOQ76p3RvFdvArymjD8N5LLlaMPLf2vEszREgNX1ZFke3v4hweD9y3SrtHoXtF1+vQAMVcAuzFknsrKjcrHUxxDSuvtBm779jLcxkqgunQ22wKsbkGOf7VwboJuHZzlnWPyAHZtfeA+8MyZ0wPhU6pDQbY4iDPZCcKuPA="
    on:
      tags: true
      condition: $DEPLOY_PYPI = "true"

install:
  - pip install -r requirements.txt
  - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
  - pip install --force-reinstall pylint==1.9.2

script:
  - pylint adafruit_msa301.py
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
  - circuitpython-build-bundles --filename_prefix adafruit-circuitpython-msa301 --library_location .
  - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
