# Generated by Django 2.2.5 on 2019-09-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_web_rich_object', '0009_auto_20161230_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrichobject',
            name='audio',
            field=models.TextField(blank=True, null=True, verbose_name='audio'),
        ),
    ]
