# Generated by Django 2.2.5 on 2019-09-13 12:25

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('dj_web_rich_object', '0010_webrichobject_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrichobject',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
