# Generated by Django 2.2.5 on 2019-09-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_web_rich_object', '0012_auto_20190916_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dj_web_rich_object.Tag'),
        ),
    ]
