# Generated by Django 2.2.5 on 2019-09-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_web_rich_object', '0013_tag_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
    ]
