# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CL.cleverlab.ai.laboratory-note-maker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CL.cleverlab.ai.laboratory-note-maker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+CL.cleverlab.ai.laboratory-note-maker.proto\"6\n\x04Note\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x11\n\tTimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\t\"\'\n\x10StoreNoteRequest\x12\x13\n\x04Note\x18\x01 \x01(\x0b\x32\x05.Note\"\x1f\n\x11StoreNoteResponse\x12\n\n\x02Id\x18\x01 \x01(\x05\"3\n\x12GetNoteListRequest\x12\x0e\n\x06Offset\x18\x01 \x01(\x05\x12\r\n\x05Limit\x18\x02 \x01(\x05\"+\n\x13GetNoteListResponse\x12\x14\n\x05Notes\x18\x01 \x03(\x0b\x32\x05.Note\"\x1f\n\x11\x44\x65leteNoteRequest\x12\n\n\x02Id\x18\x01 \x01(\x05\"1\n\x0f\x45\x64itNoteRequest\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x12\n\nNewcontent\x18\x02 \x01(\tb\x06proto3')
)




_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='Note.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='Note.Timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='Note.Content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=101,
)


_STORENOTEREQUEST = _descriptor.Descriptor(
  name='StoreNoteRequest',
  full_name='StoreNoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Note', full_name='StoreNoteRequest.Note', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=142,
)


_STORENOTERESPONSE = _descriptor.Descriptor(
  name='StoreNoteResponse',
  full_name='StoreNoteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='StoreNoteResponse.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=175,
)


_GETNOTELISTREQUEST = _descriptor.Descriptor(
  name='GetNoteListRequest',
  full_name='GetNoteListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Offset', full_name='GetNoteListRequest.Offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Limit', full_name='GetNoteListRequest.Limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=228,
)


_GETNOTELISTRESPONSE = _descriptor.Descriptor(
  name='GetNoteListResponse',
  full_name='GetNoteListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Notes', full_name='GetNoteListResponse.Notes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=273,
)


_DELETENOTEREQUEST = _descriptor.Descriptor(
  name='DeleteNoteRequest',
  full_name='DeleteNoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='DeleteNoteRequest.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=306,
)


_EDITNOTEREQUEST = _descriptor.Descriptor(
  name='EditNoteRequest',
  full_name='EditNoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='EditNoteRequest.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Newcontent', full_name='EditNoteRequest.Newcontent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=357,
)

_STORENOTEREQUEST.fields_by_name['Note'].message_type = _NOTE
_GETNOTELISTRESPONSE.fields_by_name['Notes'].message_type = _NOTE
DESCRIPTOR.message_types_by_name['Note'] = _NOTE
DESCRIPTOR.message_types_by_name['StoreNoteRequest'] = _STORENOTEREQUEST
DESCRIPTOR.message_types_by_name['StoreNoteResponse'] = _STORENOTERESPONSE
DESCRIPTOR.message_types_by_name['GetNoteListRequest'] = _GETNOTELISTREQUEST
DESCRIPTOR.message_types_by_name['GetNoteListResponse'] = _GETNOTELISTRESPONSE
DESCRIPTOR.message_types_by_name['DeleteNoteRequest'] = _DELETENOTEREQUEST
DESCRIPTOR.message_types_by_name['EditNoteRequest'] = _EDITNOTEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'CL.cleverlab.ai.laboratory_note_maker_pb2'
  # @@protoc_insertion_point(class_scope:Note)
  })
_sym_db.RegisterMessage(Note)

StoreNoteRequest = _reflection.GeneratedProtocolMessageType('StoreNoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _STORENOTEREQUEST,
  '__module__' : 'CL.cleverlab.ai.laboratory_note_maker_pb2'
  # @@protoc_insertion_point(class_scope:StoreNoteRequest)
  })
_sym_db.RegisterMessage(StoreNoteRequest)

StoreNoteResponse = _reflection.GeneratedProtocolMessageType('StoreNoteResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORENOTERESPONSE,
  '__module__' : 'CL.cleverlab.ai.laboratory_note_maker_pb2'
  # @@protoc_insertion_point(class_scope:StoreNoteResponse)
  })
_sym_db.RegisterMessage(StoreNoteResponse)

GetNoteListRequest = _reflection.GeneratedProtocolMessageType('GetNoteListRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETNOTELISTREQUEST,
  '__module__' : 'CL.cleverlab.ai.laboratory_note_maker_pb2'
  # @@protoc_insertion_point(class_scope:GetNoteListRequest)
  })
_sym_db.RegisterMessage(GetNoteListRequest)

GetNoteListResponse = _reflection.GeneratedProtocolMessageType('GetNoteListResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETNOTELISTRESPONSE,
  '__module__' : 'CL.cleverlab.ai.laboratory_note_maker_pb2'
  # @@protoc_insertion_point(class_scope:GetNoteListResponse)
  })
_sym_db.RegisterMessage(GetNoteListResponse)

DeleteNoteRequest = _reflection.GeneratedProtocolMessageType('DeleteNoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETENOTEREQUEST,
  '__module__' : 'CL.cleverlab.ai.laboratory_note_maker_pb2'
  # @@protoc_insertion_point(class_scope:DeleteNoteRequest)
  })
_sym_db.RegisterMessage(DeleteNoteRequest)

EditNoteRequest = _reflection.GeneratedProtocolMessageType('EditNoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _EDITNOTEREQUEST,
  '__module__' : 'CL.cleverlab.ai.laboratory_note_maker_pb2'
  # @@protoc_insertion_point(class_scope:EditNoteRequest)
  })
_sym_db.RegisterMessage(EditNoteRequest)


# @@protoc_insertion_point(module_scope)
