
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-15T20:51:28+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e167941e46e58040ef7b995bf46e2dd8951c2ed",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
