# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bridge
from bridge.models.bank_resource import BankResource  # noqa: E501
from bridge.rest import ApiException


class TestBankResource(unittest.TestCase):
    """BankResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankResource(self):
        """Test BankResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bridge.models.bank_resource.BankResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
