dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: tji4QRmzdVEdfwSlZWpSW+0tpFIxe539azoKWNnXcIdT+2i9iX9mMPrSAroYkmx9Fp9X4LxOAeGXLZQ6eVZQFSN/VR2GKtHfG+sErditAiacAaIfSjssTaOtYb6kWUsl5C5HN3WzG/aSC7Yq4B8meiAC8fe0o8j8/u20+GmaJgXL9zgTdWYvJygAGEI1lhR7cq+umXhHNufeFwz6/PxQzk+Tr14oEtH18r7Zf/R4h4JqCyR/1RuLFKLbPpjlEF8e0Kuxojl1N39IVtWxS5CuMeldSKaL2qj0pUbhHLzJ/LJIvxQPU3e86pta+jUkvTnhFOj9/k/dDLQxxITRwFFdDq4k8XpMVArytSoFNxQd7Fau/wIH0ALMzyE4Dvah8EFLlqPiVXj9qaFibxNhQ/oO5eGjV7Br/dQ+hau+k7zpgVzCytTWBwh6CeQ7cqUqL/QMmHy36J9lMEqFpwH7/kZRROvXjP9GLcKQuIK1sLi/telKmojtzA+ZdsNoq+tD3ZWiuTRXNIBbs/ROOnyYRExELyrpbX0RG69pu6a4Hw5ez83zrIDzaX52F0Yac75YxLlYPMOa7tWz1cvd+TJyaei8NVFQnHOopTelJtBqG9ravDkDr++TBZhxzEGI/+3u03mwB7w7AsZVLKAXKpOVI5rHvISS00k984z4R9bftI0gGTU=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint --disable=missing-docstring adafruit_thermal_printer/*.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-thermal-printer
  --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
