# Advise GitLab that these environment vars should be loaded from the Variables config.
variables:
  PYPI_USER: SECURE
  PYPI_PASSWORD: SECURE

stages:
  - lint
  - deploy

default:
  before_script:
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py
    - pip install tox

linting:
  image: python:3.7
  stage: lint
  before_script:
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py
    - pip install tox pre-commit
  script: tox -e lint
  except:
    - /^v\d+\.\d+(\.\d+([abc]\d*)?)?$/  # PEP-440 compliant

deploy_pypi:
  stage: deploy
  script:
    - echo "[distutils]" > ~/.pypirc
    - echo "index-servers =" >> ~/.pypirc
    - echo "  pypi" >> ~/.pypirc
    - echo >> ~/.pypirc
    - echo "[pypi]" >> ~/.pypirc
    - echo "username=" ${PYPI_USER} >> ~/.pypirc
    - echo "password=" ${PYPI_PASSWORD} >> ~/.pypirc
    - tox -e release
    - echo > ~/.pypirc
  after_script:
    - rm -vf ~/.pypirc
  only:
    - /^v\d+\.\d+(\.\d+([abc]\d*)?)?$/  # PEP-440 compliant
  except:
    - branches
