
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-17T21:22:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "992949d90a5a1f3d35a17b104a83785e746fa421",
 "version": "0.post.dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
