
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-11T00:25:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6445321d78bc7f3a795cdf7c71a45731dcffbee",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
