version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  basic:
    format: '%(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  pycrunch.runner:
    level: DEBUG
  pycrunch.api.socket_handlers:
    level: DEBUG
  pycrunch.watcher:
    level: INFO
  watchgod:
    level: DEBUG
  pycrunch.api:
    level: INFO
  pycrunch.shared.models:
    level: INFO
  pycrunch.api.endpoints:
    level: WARN
  pycrunch:
    level: DEBUG
  sampleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
  werkzeug:
    level: ERROR

root:
  level: DEBUG
  handlers: [console]

#xx    x
#xx    x
#xx    x
#xx    x
