[tool.poetry]
name = "po_case_conversion"
version = "0.4.0"
description = "Convert between different types of cases (unicode supported)"
authors = ["Alejandro Frias <joker454@gmail.com>", "Philip Olson <philip.olson@pm.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/olsonpm/py_case-conversion"
include = [
  "po_case_conversion/LICENSE.txt",
  "po_case_conversion/top_level.txt"
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
toml = "^0.10.0"
is_git_repo_clean = "^0.3.4"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
