#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['dataclassesapi']

package_data = \
{'': ['*'], 'dataclassesapi': ['tests/*']}

install_requires = \
['dataclassesjson[orjson]']

extras_require = \
{'doc': ['mkdocs', 'mkdocs-material', 'markdown-include'],
 'test': ['asgi-testclient',
          'bumpversion',
          'black',
          'flake8',
          'isort',
          'ipython',
          'mypy',
          'pytest-asyncio',
          'pytest-cov',
          'pytest-mock',
          'pytest>=5.1.1',
          'tox',
          'towncrier',
          'uvicorn']}

setup(name='dataclassesapi',
      version='0.1.1',
      description='ASGI App using dataclasses module for request/response objects',
      author='Diogo Dutra',
      author_email='diogodutradamata@gmail.com',
      url='https://github.com/dutradda/dataclassesapi',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
