# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20170519_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='status',
            field=models.CharField(choices=[(b'alive', b'alive'), (b'dead', b'dead'), (b're-entered', b're-entered')], default=b'alive', max_length=10),
        ),
    ]
