# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-09-23T21:01:18.110231'

__version__ = '2019.9.3'
__sha__ = '07a6f11fba846ab8939b7d35c4ea4b6d46f18701'
__revision__ = '07a6f11fba846ab8939b7d35c4ea4b6d46f18701'
