# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=64)),
                ('updateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CaeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=64)),
                ('userNameSuffix', models.CharField(default='', max_length=32)),
                ('quota', models.IntegerField()),
                ('cpuTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThiThirdApp',
            fields=[
                ('appId', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('appKey', models.CharField(max_length=64)),
                ('appName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginToken', models.CharField(max_length=64)),
                ('userName', models.CharField(max_length=64)),
                ('displayUserName', models.CharField(max_length=64, null=True)),
                ('updateTime', models.DateTimeField()),
                ('thiThirdApp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thjwt.ThiThirdApp')),
            ],
        ),
        migrations.AddField(
            model_name='caeaccount',
            name='thiThirdApp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thjwt.ThiThirdApp'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='thiThirdApp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thjwt.ThiThirdApp'),
        ),
    ]
