[tool.poetry]
name = "make-help"
version = "0.1.1"
description = ""
authors = ["Sam Bishop <sam@techdragon.io>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
click-pathlib = "^2019.6.13"
colorama = "^0.4.1"
click-log = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest_click = "^0.3"

[tool.poetry.scripts]
make-help = 'make_help.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
