# Generated by Django 2.2.4 on 2019-09-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HGIOURSTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_number', models.CharField(default='1', max_length=1)),
                ('theme_name', models.CharField(default='HGIOURS Theme', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NIFDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif_driver', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NIFPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif_priority', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='QI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qi_number', models.CharField(default='x.x', max_length=5)),
                ('qi_text', models.CharField(max_length=150)),
                ('qi_long_description', models.CharField(default='QI long description text', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_number', models.CharField(default='x.x', max_length=10)),
                ('theme_name', models.CharField(max_length=200)),
                ('theme_long_description', models.CharField(default='Theme long description text', max_length=1500)),
                ('nif_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.NIFDriver')),
                ('nif_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.NIFPriority')),
                ('qi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.QI')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_feature', models.CharField(blank=True, default='', max_length=200)),
                ('exemplification_header', models.CharField(default='', max_length=175)),
                ('user_type', models.CharField(default='Teacher', max_length=10)),
                ('primary_only', models.BooleanField(default=False)),
                ('secondary_only', models.BooleanField(default=False)),
                ('is_departmental', models.BooleanField(default=False)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureExemplification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemplification', models.CharField(max_length=200)),
                ('user_type', models.CharField(default='Teacher', max_length=10)),
                ('primary_only', models.BooleanField(default=False)),
                ('secondary_only', models.BooleanField(default=False)),
                ('is_departmental', models.BooleanField(default=False)),
                ('theme_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ThemeFeature')),
            ],
        ),
    ]
