# Generated by Django 2.2.3 on 2019-09-18 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("edc_action_item", "0022_auto_20190628_2136"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meta_prn", "0004_auto_20190918_0200"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalUnblindingApproval",
            new_name="HistoricalUnblindingReview",
        ),
        migrations.RenameModel(
            old_name="UnblindingApproval", new_name="UnblindingReview"
        ),
        migrations.AlterModelOptions(
            name="historicalunblindingreview",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Unblinding Review",
            },
        ),
        migrations.AlterModelOptions(
            name="unblindingreview",
            options={
                "verbose_name": "Unblinding Review",
                "verbose_name_plural": "Unblinding Reviews",
            },
        ),
        migrations.RemoveIndex(
            model_name="unblindingreview", name="meta_prn_un_subject_64fb4a_idx"
        ),
        migrations.AddIndex(
            model_name="unblindingreview",
            index=models.Index(
                fields=["subject_identifier", "action_identifier", "site", "id"],
                name="meta_prn_un_subject_b4c71f_idx",
            ),
        ),
    ]
