repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length, "100"]
        language_version: python3.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.22.1
    hooks:
      - id: pyupgrade
  - repo: local
    hooks:
      - id: system-pylint
        name: pylint
        description: pylint hook
        entry: python -m pylint.__main__
        files: \.py$
        language: system
