# Generated by Django 2.2.5 on 2019-09-22 18:25

import blockmodelbackend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_atempts_number', models.IntegerField(default=0)),
                ('last_atempt', models.DateTimeField(null=True)),
                ('lock_duration', models.DurationField(default=blockmodelbackend.models.default_block_duration)),
                ('prev_locks_number', models.IntegerField(default=0)),
                ('permanent_block', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_atempts_number', models.IntegerField(default=0)),
                ('last_atempt', models.DateTimeField(null=True)),
                ('lock_duration', models.DurationField(default=blockmodelbackend.models.default_block_duration)),
                ('prev_locks_number', models.IntegerField(default=0)),
                ('permanent_block', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
