
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-13T11:02:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "560e1038e620cd10557ed499b8e57b2f07f9db72",
 "version": "3.0.68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
