# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galacteek/ui/ipfssearchw.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IPFSSearchMain(object):
    def setupUi(self, IPFSSearchMain):
        IPFSSearchMain.setObjectName("IPFSSearchMain")
        IPFSSearchMain.resize(779, 463)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(IPFSSearchMain)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(IPFSSearchMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.searchQuery = QtWidgets.QLineEdit(IPFSSearchMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchQuery.sizePolicy().hasHeightForWidth())
        self.searchQuery.setSizePolicy(sizePolicy)
        self.searchQuery.setObjectName("searchQuery")
        self.horizontalLayout_3.addWidget(self.searchQuery)
        self.label = QtWidgets.QLabel(IPFSSearchMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.contentTypeFilter = QtWidgets.QComboBox(IPFSSearchMain)
        self.contentTypeFilter.setObjectName("contentTypeFilter")
        self.horizontalLayout_3.addWidget(self.contentTypeFilter)
        self.moreFilters = QtWidgets.QToolButton(IPFSSearchMain)
        self.moreFilters.setCheckable(True)
        self.moreFilters.setObjectName("moreFilters")
        self.horizontalLayout_3.addWidget(self.moreFilters)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.prevPageButton = QtWidgets.QPushButton(IPFSSearchMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevPageButton.sizePolicy().hasHeightForWidth())
        self.prevPageButton.setSizePolicy(sizePolicy)
        self.prevPageButton.setMinimumSize(QtCore.QSize(40, 0))
        self.prevPageButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.prevPageButton.setText("")
        self.prevPageButton.setObjectName("prevPageButton")
        self.horizontalLayout_3.addWidget(self.prevPageButton)
        self.nextPageButton = QtWidgets.QPushButton(IPFSSearchMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextPageButton.sizePolicy().hasHeightForWidth())
        self.nextPageButton.setSizePolicy(sizePolicy)
        self.nextPageButton.setMinimumSize(QtCore.QSize(40, 0))
        self.nextPageButton.setMaximumSize(QtCore.QSize(40, 40))
        self.nextPageButton.setText("")
        self.nextPageButton.setObjectName("nextPageButton")
        self.horizontalLayout_3.addWidget(self.nextPageButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.filtersWidget = QtWidgets.QWidget(IPFSSearchMain)
        self.filtersWidget.setObjectName("filtersWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.filtersWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.filtersLayout = QtWidgets.QGridLayout()
        self.filtersLayout.setHorizontalSpacing(12)
        self.filtersLayout.setObjectName("filtersLayout")
        self.label_3 = QtWidgets.QLabel(self.filtersWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.filtersLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.filenameFilter = QtWidgets.QLineEdit(self.filtersWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameFilter.sizePolicy().hasHeightForWidth())
        self.filenameFilter.setSizePolicy(sizePolicy)
        self.filenameFilter.setMaximumSize(QtCore.QSize(200, 16777215))
        self.filenameFilter.setObjectName("filenameFilter")
        self.filtersLayout.addWidget(self.filenameFilter, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.filtersWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.filtersLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.titleFilter = QtWidgets.QLineEdit(self.filtersWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleFilter.sizePolicy().hasHeightForWidth())
        self.titleFilter.setSizePolicy(sizePolicy)
        self.titleFilter.setMaximumSize(QtCore.QSize(200, 16777215))
        self.titleFilter.setObjectName("titleFilter")
        self.filtersLayout.addWidget(self.titleFilter, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.filtersWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.filtersLayout.addWidget(self.label_5, 0, 7, 1, 1)
        self.lastSeenSlider = QtWidgets.QSlider(self.filtersWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastSeenSlider.sizePolicy().hasHeightForWidth())
        self.lastSeenSlider.setSizePolicy(sizePolicy)
        self.lastSeenSlider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lastSeenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lastSeenSlider.setObjectName("lastSeenSlider")
        self.filtersLayout.addWidget(self.lastSeenSlider, 0, 8, 1, 1)
        self.lastSeenLabel = QtWidgets.QLabel(self.filtersWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastSeenLabel.sizePolicy().hasHeightForWidth())
        self.lastSeenLabel.setSizePolicy(sizePolicy)
        self.lastSeenLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lastSeenLabel.setText("")
        self.lastSeenLabel.setObjectName("lastSeenLabel")
        self.filtersLayout.addWidget(self.lastSeenLabel, 0, 9, 1, 1)
        self.gridLayout.addLayout(self.filtersLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.filtersWidget)
        self.browser = QtWebEngineWidgets.QWebEngineView(IPFSSearchMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browser.sizePolicy().hasHeightForWidth())
        self.browser.setSizePolicy(sizePolicy)
        self.browser.setAutoFillBackground(False)
        self.browser.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 0, 0, 255), stop:0.479904 rgba(255, 0, 0, 255), stop:0.522685 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.browser.setUrl(QtCore.QUrl("about:blank"))
        self.browser.setObjectName("browser")
        self.verticalLayout_2.addWidget(self.browser)

        self.retranslateUi(IPFSSearchMain)
        QtCore.QMetaObject.connectSlotsByName(IPFSSearchMain)

    def retranslateUi(self, IPFSSearchMain):
        _translate = QtCore.QCoreApplication.translate
        IPFSSearchMain.setWindowTitle(_translate("IPFSSearchMain", "Form"))
        self.label_2.setText(_translate("IPFSSearchMain", "Search"))
        self.label.setText(_translate("IPFSSearchMain", "Content type"))
        self.moreFilters.setText(_translate("IPFSSearchMain", "More filters"))
        self.label_3.setText(_translate("IPFSSearchMain", "Filename search"))
        self.label_6.setText(_translate("IPFSSearchMain", "Title"))
        self.label_5.setText(_translate("IPFSSearchMain", "Last seen"))

from PyQt5 import QtWebEngineWidgets
