dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: h196AUXN5VkIU3bAuMhkGMXKvlsAIJybx3U1cxpTUjYCGe/f6Uh+tDS8DCcLQN5dV58DEMZ7TSo/gogrb4/S7cdzGt/GC0a6OwQu5XsywnqaFtnVSLF0SocUcywd8MEJSmBrjf/vDI2s6o7hVhZPuy60h6Own1/jJOGCgYuySyBYNQfqIpu4NPcOjslNbEz2I9YPK8bcQxM4vLaF4ywEeFzQquCqm2r8cRKN0BUsmEKsCgvdJeIscc0kNKKkSbiJe6wzXSkK6dNGHti1NHH/w4yFoJGMh3A1hkPrWkuIHnw3pySz1jyeeYLpWcMRbh4+x4pKBUDOaezkh6b42LfBg3+B1QbshUNen/CC6GALihfJgJquU9K9MSSNRqsWN1itL4PO0RN67NynrJvd7W/rhekZzoVu3o0UgF7iPhahUl1PMqF47R2jx9YmrRxkYNYgR22fYbNFeXOIJTfx74+F4LJvxpjcXZfccjIlTkuWzM+bngQTtJYw6cpcRnrktUz4arkkerxlmwRUBPWpTP2YTnj6k9Zhwznvf6iM+ssL8SICmNlLzj2FB5hf2f4dpAymABBwouKRHljbRxquGbBPrYMS2p5vBU2ZmgsvJ7NMxIuk7F5o+2rLzHUbHUBiuVDL60uSP3McUwRus0Kv6ToUnmz0YLcYH8u/g4t0vSUs/8c=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_sht31d.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-sht31d --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
