[tool.poetry]
name = "preacher"
version = "0.9.9"
description = "A web API verification tool."
authors = ["Yu Mochizuki <ymoch.dev@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/ymoch/preacher"
license = "MIT"

[tool.poetry.scripts]
preacher-cli = "preacher.app.cli.main:main"

[tool.poetry.dependencies]
python = "^3.7"
aniso8601 = "^8.0"
pyhamcrest = "^1.9"
pyjq = "^2.3"
requests = "^2.21"
"ruamel.yaml" = "^0.15.89"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
pytest-runner = "^4.4"
pytest-flakes = "^4.0"
pytest-pycodestyle = "^1.4"
pytest-mypy = "^0.3.2"
pytest-cov = "^2.6"
responder = "^1.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
