[tool.poetry]
name = "initable"
version = "0.1.2"
description = "Initable is a Python package that helps create DRY-er classes."
authors = ["Payson Wallach <paysonwallach@icloud.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.3"

[tool.poetry.dev-dependencies]
pytest = "^5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
