
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0321d43bcfbd8da0cc2cd3ce3a1204cfa130cc52",
 "version": "2190"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
