
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-06T11:44:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ccb9aa9c8a3b5d5634a130ae883cebbc1c518f3",
 "version": "v0.6a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
