[tool.poetry]
name = "instru"
version = "0.1.1"
description = ""
authors = ["James Maxwell"]

[tool.poetry.dependencies]
python = "^3.7"
qcodes = "^0.5.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
demo = "instru:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

