[tool.poetry]
name = "FrontApp"
version = "0.1.1"
description = ""
authors = ["MB <mb@m1k.pw>"]

[tool.poetry.dependencies]
python = "^3.7"
attrs = "^19.1"
requests = "^2.22"
envparse = "^0.2.0"
decorator = "^4.4"
fastapi = "^0.38.1"
uvicorn = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = ">=19.3b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
