environment:
  n_semitones: 13
  n_roll_steps: 30
  n_observed_roll_steps: 4
  max_n_stalled_episode_steps: 5
  scoring_coefs:
    horizontal_variance: 2
    vertical_variance: 1
    repetitiveness: 25
    consonances: 1
  scoring_fn_params:
    consonances:
      interval_consonances:
        0: 2
        1: -3
        2: -3
        3: 1
        4: 1
        5: 0
        6: -5
        7: 2
        8: 1
        9: 1
        10: -3
        11: -3
      distance_weights:
        0: 1
        1: 1
        2: 0.5
        3: 0.25
  rendering_params:
    dir: rlmusician_data
    sinethesizer:
      timbre: fm_sine
      lowest_note: C4
      step_in_seconds: 0.5
      volume: 0.1
agent:
  population_size: 100
  elite_fraction: 0.1
  n_episodes_per_candidate: 10
  aggregation_fn: mean
  weights_std: 1.0
  n_warmup_candidates: 0
