# coding: utf-8

"""
    Budgea API Documentation

    see https://www.budget-insight.com/budgea-api  # noqa: E501

    OpenAPI spec version: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import budgea
from budgea.models.transfer import Transfer  # noqa: E501
from budgea.rest import ApiException


class TestTransfer(unittest.TestCase):
    """Transfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransfer(self):
        """Test Transfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = budgea.models.transfer.Transfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
