
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-09T11:00:46-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "079552128eee6102646d1cc62f83b9a30cc3e3dd",
 "version": "0.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
