dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: VzcZN7a3TCXrl25vcMJgGCKRyKF9K6MwaPCdUjp9Cjnp9hvUNrwUysCq1kNaHBdiIEiInHvaqNT5bIg8cXJi+Hzh9K9E458pbzyQPJdnWbW98ONe//tJUpfrPW/dNdGtnrpEzm7B9+s9g1IV4fXgnRRnmWGdxBOzRTOCIZd37kUkGh6DqwGEIz97RsR3Upv2T4i7IKXkUSYaY16G+qtStkLvPIY9FERVN5RcBNuMEc5r3EGEDXe3iXiMHRyxKtR5Tk3LtVHae8a/N+4t1l3Finn+hO9xCXzXaDwJuBrDj6arVVEZdBoszdVIOgT+3aAdCDYf1/jJG/Blwn5GJWf+wiSUziDogC+npDD0siHVgdIRaymhVDHqRbgXrUkO0kM2zASk1lLQPqYSn4alV1Qm1B3zs7gVyB/mvgqm6jlkx40q8mg7AbR9wx03s1NqZyp4HGB9gJ8DcoP7y7oGWHynY3dOxXzpKnhbkslB068YMk7YC9JDFmVQhgwRNxcq3OGY2zSDOp+j7+2KAS7bqsKnrnGN8YYw7Qn2Igo6Xtm8XkuNlz14pB6Uqe8tyzDVDIBGmuKo7MnF5ndtg8goIdMhK03W4O10t8K1lOGTk9wBco9yS/yK7Gg8a0geRS16+Yq7GQ5LyJqB5Sn85w2b+GdhWByXyMGCxvWoKmLidU5KN9s=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_fxas21002c.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-fxas21002c
  --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
