
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-18T20:12:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9d76b306574511577e138e85e2c8b1d5766e05e",
 "version": "0.3.1.post.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
