language: python
dist: xenial
python:
  - 3.7

stages:
  - test
  - name: deploy
    if: (branch = master) AND (tag =~ ^v\d+.*$)
env:
  global:
  - TRAVIS_RUST_VERSION=nightly-2019-07-01
  - RUST_BACKTRACE=1

test_template: &test_template
  stage: test
  before_install:
    - source ./ci/travis/setup_rust.sh
  install:
    - make install-dev
  script:
    - make test

jobs:
  include:
    - <<: *test_template
      name: "test py36"
      python: 3.6
    - <<: *test_template
      name: "test py37"
    - stage: deploy
      addons:
        apt:
          packages:
            - python3.6
      before_install:
        - source ./ci/travis/setup_rust.sh
      install:
        - pip install maturin==0.7.2
      script:
        - maturin publish -u pattonw -p PYPI_PASSWORD -i python3.6 -i python3.7
