[tool.poetry]
name = "aioli-rdbms"
version = "0.3.0"
description = "ORM and CRUD Service for Aioli with support for MySQL and PostgreSQL"
authors = ["Robert Wikman <rbw@vault13.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/aioli-framework/aioli-rdbms"
keywords = ["aioli_package"]

[tool.poetry.dependencies]
python = "^3.6"
aioli = "^0.5.0"
orm = "~0.1"
databases = "^0.2.1"
asyncpg = "^0.18.3"
psycopg2-binary = "^2.8.1"
aiomysql = "^0.0.20"
mysqlclient = "^1.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
