testmod_task:
  container:
    image: python:3

  setup_script:
    - pip install .
  script:
    - python -m testmod
 

test_task:
  container:
    image: python:3
  script:
    - python setup.py test


flake8_task:
  container:
    image: python:3
  setup_script:
    - pip install flake8
  script:
    - flake8


docs_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  container:
    image: python:3

  install_script:
    - pip install --upgrade-strategy eager -U -r docs/requirements.txt
    - pip install -e .

  script:
    - make -C docs/ linkcheck
    - make -C docs/ html



build_task:
  container:
    image: python:3
  setup_script:
    - pip install bork
  script:
    - bork build
  dist_artifacts:
    path: "dist/**"
 

upload_task:
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_RELEASE != ''
  depends_on:
    - build
    - test
    - flake8
    - testmod
  env:
    TWINE_TEST_TOKEN: "ENCRYPTED[8ec827e766c7e19734e4bbc99ecc8268a4c709b66330bc99224122c7a51fcfe876780b1e6e3fe2c4f882498aa02cb414]"
    TWINE_PROD_TOKEN: "ENCRYPTED[2a53ff981febc4681374ab796f421010e11dc6682b89f029197d4204362c16fb4ca0f522b6df362fe80917e3342b5fbf]"
    GITHUB_TOKEN: "ENCRYPTED[41ec9f206bf2335966d2e0c873c1b57771a2a3160a7a0a277583c415124422ae5a581771fee88d32e51f034c3a0fd38c]"

  container:
    image: xonsh/xonsh:slim

  install_script:
    - pip install twine

  script:
    - xonsh .ci/upload.xsh
