
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-10T10:39:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a949d7985616435fa41d91adf0058e1fb9c066f",
 "version": "0.0.54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
