# Generated by Django 2.2.2 on 2019-07-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psu_base', '0002_remove_infotext_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infotext',
        ),
    ]
