# Generated by Django 2.2.4 on 2019-08-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_base', '0004_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(help_text='Application that this audit belongs to.', max_length=15, verbose_name='Application Code')),
                ('event_code', models.CharField(help_text='This string should uniquely identify the type of event', max_length=80)),
                ('username', models.CharField(help_text='This holds the username of the event performer, which could be a provisional email address', max_length=128)),
                ('previous_value', models.CharField(blank=True, default=None, help_text='Value before change was made', max_length=500, null=True)),
                ('new_value', models.CharField(blank=True, default=None, help_text='Value after change was made', max_length=500, null=True)),
                ('comments', models.CharField(blank=True, default=None, help_text='Comments about the event', max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
