# Generated by Django 2.2.4 on 2019-08-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_base', '0005_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='admin_proxy_username',
            field=models.CharField(blank=True, default=None, help_text='This holds the username of the selected admin proxy, if the user is admin proxying', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='proxy_username',
            field=models.CharField(blank=True, default=None, help_text='This holds the username of the selected proxy, if the user is proxying', max_length=128, null=True),
        ),
    ]
