# coding: utf-8

"""
    Felix' Website mit Blog

    The api of my blog.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: felix@felix-scholz.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

from website_python_client.models.file import File


class TestFile(unittest.TestCase):
    """File unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_constructor(self):
        identifier = File.hash_identifier('test-1')
        f = File(identifier)

        self.assertEqual(identifier, f.identifier)


if __name__ == '__main__':
    unittest.main()
