# coding: utf-8

"""
    Felix' Website mit Blog

    The api of my blog.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: felix@felix-scholz.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest


class TestPost(unittest.TestCase):
    """Post unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPost(self):
        """Test Post"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.post.Post()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
