[tool.poetry]
name = "po_simple_test"
version = "0.5.0"
description = "A simple test runner"
authors = ["Philip Olson <philip.olson@pm.me>"]
license = "WTFNMFPL-1.0"
readme = "README.md"
repository = "https://github.com/olsonpm/py_simple-test"
include = [
  "po_simple_test/license.txt",
  "po_simple_test/top_level.txt"
]

[tool.poetry.scripts]
simple-test = "po_simple_test.script:main"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
num2words = "^0.5.8"
simple_chalk = "^0.1.0"
pretty_simple_namespace = "^0.1.0"
toml = "^0.10.0"
is_git_repo_clean = "^0.3.4"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
simple_test_process = "^0.5.0"
po_case_conversion = "^0.4.0"

[tool.vendorize]
target = "po_simple_test/_vendor"
packages = [
  "wrapt >=1.10,<1.11",
  "ordered_set >=3.1,<3.2",
  "tedent >=0.1.1,<0.2",
  "simple_test_process >=0.5,<0.6",
  "po_case_conversion >=0.4,<0.5"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
