[tool.poetry]
name = "ankilist"
version = "0.1.6"
description = "Lite google translate console client and anki list generator"
authors = ["VladislavNekto <vladislav.nekto.dev@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "3.7.4"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
ankilist = 'ankilist:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
