[tool.black]
line-length = 88
target-version = ['py37', 'py38']

[tool.poetry]
name = "roax-postgis"
module = "roax.postgis"
version = "2.0a1"
description = "PostGIS extension for Roax."
readme = "README.md"
authors = ["Paul Bryan <pbryan@anode.ca>"]
homepage = "https://github.com/roax/roax-postgis/"
license = "MIT"
keywords = ["wsgi", "framework", "resource", "openapi"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
packages = [
    { include = "roax" }
]

[tool.poetry.dependencies]
python = "^3.7 <3.8"
roax-postgresql = "^2.0a1"
roax-geo = "^2.0a1"

[tool.poetry.dev-dependencies]
black = "^19.3b0"
pre-commit = "^1.18"
pytest = "^5.1"
pytest-cov = "^2.7"
