[tool.poetry]
name = "envtoml"
version = "0.1.0"
description = ""
authors = ["mr.Shu <mr@shu.io>"]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
nose = "^1.3"
coverage = "^4.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
