# Generated by Django 2.2.5 on 2019-09-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactfields',
            options={'ordering': ['id'], 'verbose_name': 'Поле контактов', 'verbose_name_plural': 'Поля контактов'},
        ),
    ]
