
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-13T11:04:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b316a978793d0d6a9d38a928d94c2aef0bb9795e",
 "version": "1.38.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
