# Generated by Django 2.2.4 on 2019-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190902_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_overview_help',
            field=models.BooleanField(default=True),
        ),
    ]
