stages:
  - test
  - staging
  - deploy


centos7:
  stage: test
  except:
    - tags
  image: gitlab-registry.cern.ch/lhcb-docker/rabbitmq-python-deployment:centos7
  script:
    - init.sh # For RabbitMQ Usage
    - python --version
    - pip install pycodestyle importlib nose coverage
    - pip install .
    - nosetests --with-coverage --cover-package=lbciagent --cover-html --with-xunit --exe
    - pycodestyle lbinstall/ > pep8_report.txt || true
    - mkdir -p cover_report && mv -f cover cover_report/$CI_JOB_NAME
    - mkdir -p pep8_report && mv -f pep8_report.txt pep8_report/$CI_JOB_NAME.txt
  artifacts:
    paths:
      - cover_report
      - pep8_report
    when: always
    expire_in: 1 week
  tags:
    - cvmfs


python2.7:
  stage: test
  image: gitlab-registry.cern.ch/lhcb-docker/rabbitmq-python-deployment:python-2.7
  script:
    - init.sh # For RabbitMQ Usage
    - python --version
    - pip install pycodestyle importlib nose coverage
    - pip install .
    - nosetests --with-coverage --cover-package=lbciagent --cover-html --with-xunit --exe
    - pycodestyle lbinstall/ > pep8_report.txt || true
    - mkdir -p cover_report && mv -f cover cover_report/$CI_JOB_NAME
    - mkdir -p pep8_report && mv -f pep8_report.txt pep8_report/$CI_JOB_NAME.txt
  artifacts:
    paths:
      - cover_report
      - pep8_report
    when: always
    expire_in: 1 week
  tags:
    - cvmfs

checkDeploymentPolicy:
  stage: staging
  image: gitlab-registry.cern.ch/lhcb-docker/rabbitmq-python-deployment:python-2.7
  script:
    - init.sh # For RabbitMQ Usage
    - python --version
    - export PYTHONPATH="${PYTHONPATH}:/cvmfs/lhcb.cern.ch/lib/lhcb/LBSCRIPTS/LBSCRIPTS_v9r2p4/InstallArea/python"
    - git clone https://gitlab.cern.ch/lhcb-core/LHCbNightlyConf.git
    - pip install pycodestyle importlib nose coverage
    - pip install .
    - nosetests --with-coverage --cover-package=lbciagent --cover-html --with-xunit --exe
    - python lbciagent/scripts/checkDeploymentPolicy.py ./LHCbNightlyConf
    - python setup.py sdist --dist-dir public/lbciagent
  artifacts:
    paths:
      - public
    when: always
    expire_in: 1 week
  tags:
    - cvmfs

python3.5:
  stage: test
  except:
    - tags
  image: gitlab-registry.cern.ch/lhcb-docker/rabbitmq-python-deployment:python-3.5
  script:
    - init.sh # For RabbitMQ Usage
    - python --version
    - pip install pycodestyle nose coverage
    - pip install .
    - nosetests --with-coverage --cover-package=lbciagent --cover-html --with-xunit --exe
    - pycodestyle lbinstall/ > pep8_report.txt || true
    - mkdir -p cover_report && mv -f cover cover_report/$CI_JOB_NAME
    - mkdir -p pep8_report && mv -f pep8_report.txt pep8_report/$CI_JOB_NAME.txt
  artifacts:
    paths:
      - cover_report
      - pep8_report
    when: always
    expire_in: 1 week
  tags:
    - cvmfs

python3.6:
  stage: test
  except:
    - tags
  image: gitlab-registry.cern.ch/lhcb-docker/rabbitmq-python-deployment:python-3.6
  script:
    - init.sh # For RabbitMQ Usage
    - python --version
    - pip install pycodestyle nose coverage
    - pip install .
    - nosetests --with-coverage --cover-package=lbciagent --cover-html --with-xunit --exe
    - pycodestyle lbinstall/ > pep8_report.txt || true
    - mkdir -p cover_report && mv -f cover cover_report/$CI_JOB_NAME
    - mkdir -p pep8_report && mv -f pep8_report.txt pep8_report/$CI_JOB_NAME.txt
  artifacts:
    paths:
      - cover_report
      - pep8_report
    when: always
    expire_in: 1 week
  tags:
    - cvmfs

# see https://gitlab.cern.ch/gitlabci-examples/deploy_eos for the details
# of the configuration
deploy-packages:
  stage: deploy
  only:
    - tags
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - test -z "$EOS_ACCOUNT_USERNAME" -o -z "$EOS_ACCOUNT_PASSWORD" -o -z "$EOS_PATH" && exit 0 || true
    # Script that performs the deploy to EOS. Makes use of the variables defined in the project
    # It will copy the generated content to the folder in EOS
    - deploy-eos
  # do not run any globally defined before_script or after_script for this step
  before_script: []
  after_script: []
