Aep = {
    "AepId",
    "AssociationRetryCount",
    "Category",
    "ContainerId",
    "DeviceAddress",
    "DiscoveryMethod",
    "FriendlyName",
    "GeneratedFriendlyName",
    "InstanceIds",
    "InterfaceClasses",
    "IsAssociatable",
    "IsAssociatableByUserAction",
    "IsAssociated",
    "IsAuthenticated",
    "IsConnected",
    "IsEncrypted",
    "IsRoamable",
    "Manufacturer",
    "ModelId",
    "ModelName",
    "Present",
    "ProtocolId",
    "ProviderAepId",
    "ProviderInstanceIds",
    "ProviderName",
    "RefreshDevicePresenceState",
    "SignalStrength",
}

AepContainer = {
    "Categories",
    "Children",
    "ContainerId",
    "DialInstalledApplications",
    "FriendlyName",
    "IsAssociatable",
    "IsAssociatableByUserAction",
    "IsAssociated",
    "Manufacturer",
    "ModelIds",
    "ModelName",
    "Present",
    "ProtocolIds",
    "SupportedUriSchemes",
    "SupportsAudio",
    "SupportsCapturing",
    "SupportsImages",
    "SupportsInformation",
    "SupportsLimitedDiscovery",
    "SupportsNetworking",
    "SupportsObjectTransfer",
    "SupportsPositioning",
    "SupportsRendering",
    "SupportsTelephony",
    "SupportsVideo",
}

AepService = {
    "AepId",
    "Category",
    "ContainerId",
    "FriendlyName",
    "ParentAepIsAssociated",
    "ProtocolId",
    "ProviderName",
    "ProviderServiceId",
    "ServiceClassFriendlyName",
    "ServiceClassId",
    "ServiceId",
}

Bluetooth = {
    "AepQuery_IssueInquiry",
    "AepQuery_LE_ActiveScanning",
    "AepQuery_LE_ScanInterval",
    "AepQuery_LE_ScanWindow",
    "AepQuery_LE_UseFilteredDiscovery",
    "AepServiceQuery_CacheMode",
    "AepServiceQuery_TargetDevice",
    "AepService_PublisherPackageName",
    "AepService_PublisherUserSecurityId",
    "AepService_ServiceGUID",
    "Association_Ext_Param_InboundBlob",
    "ClassOfDevice",
    "ClassOfDevice_Deprecated",
    "ClassOfDevice_Major",
    "ClassOfDevice_Minor",
    "ClassOfDevice_Service_Audio",
    "ClassOfDevice_Service_Capturing",
    "ClassOfDevice_Service_Information",
    "ClassOfDevice_Service_LimitedDiscovery",
    "ClassOfDevice_Service_Networking",
    "ClassOfDevice_Service_ObjectXfer",
    "ClassOfDevice_Service_Positioning",
    "ClassOfDevice_Service_Rendering",
    "ClassOfDevice_Service_Telephony",
    "DeviceAddress",
    "DeviceFlags",
    "DeviceManufacturer",
    "DeviceModelNumber",
    "DevicePID",
    "DeviceProductVersion",
    "DeviceVID",
    "DeviceVIDSource",
    "GattService_AttributeHandle",
    "IsDiscoverable",
    "L2capService_InstanceId",
    "LastConnectedTime",
    "LastConnectedTime_Deprecated",
    "LastRawSignalStrengthInDBm",
    "LastSeenTime",
    "RadioAddress",
    "RadioAreBRSecureConnectionsSupported",
    "RadioAreLESecureConnectionsSupported",
    "RadioAreProximalConnectionsSupported",
    "RadioEncryptionKeySizeEnforcementSupported",
    "RadioHciRevision",
    "RadioHciVendorFeatures",
    "RadioHciVersion",
    "RadioIsCentralRoleSupported",
    "RadioIsPeripheralRoleSupported",
    "RadioLmpSubVersion",
    "RadioLmpSupportedFeatures",
    "RadioLmpVersion",
    "RadioManufacturer",
    "RfcommService_InstanceId",
    "SecureConnectionPaired",
    "ServiceGUID",
}

BluetoothLE = {
    "AddressType",
    "Advertisement",
    "Appearance",
    "AppearanceCategory",
    "AppearanceSubcategory",
    "Connectable",
    "PrepairingDeviceId",
    "ScanResponse",
    "SecureConnectionPaired",
}

DasParam = {
    "AepStoreOnly",
    "DiscoverOnPublicNetwork",
    "PassiveScanning",
    "QueryFromAppContainerWinRT",
    "StartedFromBackgroundTask",
    "X",
}

DevQuery = {
    "ObjectType",
}

Device = {
    "AdditionalSoftwareRequested",
    "Address",
    "AvailableTime",
    "BaseContainerId",
    "BatteryLevel",
    "BatteryLow",
    "BiosDeviceName",
    "Bitrates",
    "BusNumber",
    "BusRelations",
    "BusReportedDeviceDesc",
    "BusTypeGuid",
    "CanPlayProtectedAudio",
    "Capabilities",
    "Characteristics",
    "Children",
    "Class",
    "ClassGuid",
    "CompatibleIds",
    "ConfigFlags",
    "ConfigurationId",
    "ConnectionStateIsAuthoritative",
    "ContainerId",
    "DHP_Rebalance_Policy",
    "DLNACAP",
    "DLNADOC",
    "DebuggerSafe",
    "DependencyBootSession",
    "DependencyDependents",
    "DependencyProviders",
    "DevNodeStatus",
    "DevType",
    "DeviceCompatFlags",
    "DeviceDesc",
    "DmaRemappingPolicy",
    "Driver",
    "DriverCoInstallers",
    "DriverDate",
    "DriverDesc",
    "DriverExtendedInfs",
    "DriverInGroup",
    "DriverIncludedConfigs",
    "DriverIncludedInfs",
    "DriverInfPath",
    "DriverInfSection",
    "DriverInfSectionExt",
    "DriverLogoLevel",
    "DriverNodeStrongName",
    "DriverProblemDesc",
    "DriverPropPageProvider",
    "DriverProvider",
    "DriverRank",
    "DriverSoftwareLinks",
    "DriverVersion",
    "EjectionRelations",
    "EnumeratorName",
    "Exclusive",
    "ExtendedAddress",
    "ExtendedConfigurationIds",
    "ExtraSinkProtocolInfo",
    "FirmwareDate",
    "FirmwareDependencies",
    "FirmwareRevision",
    "FirmwareVersion",
    "FirstInstallDate",
    "FriendlyName",
    "FriendlyNameAttributes",
    "GenericDriverInstalled",
    "HardwareConfigurationIndex",
    "HardwareIds",
    "HasProblem",
    "IconFileNames",
    "IconUrls",
    "InLocalMachineContainer",
    "InstallDate",
    "InstallError",
    "InstallFlags",
    "InstallInProgress",
    "InstallInf",
    "InstallState",
    "InstallStrongName",
    "InstalledSoftware",
    "InstanceId",
    "IsAssociateableByUserAction",
    "IsConnected",
    "IsLegacyDMR",
    "IsPresent",
    "IsRebootRequired",
    "LastArrivalDate",
    "LastKnownParent",
    "LastRemovalDate",
    "Legacy",
    "LegacyBusType",
    "LocationInfo",
    "LocationPaths",
    "LowerFilters",
    "Manufacturer",
    "ManufacturerAttributes",
    "MatchingDeviceId",
    "MatchingTargetComputerId",
    "MaxVolume",
    "MigrationRank",
    "Model",
    "ModelId",
    "NetworkId",
    "NoConnectSound",
    "Numa_Node",
    "Numa_Proximity_Domain",
    "OmitFromSystemSpec",
    "OverrideContainerId",
    "Owners",
    "PDOName",
    "PacketWakeFailedTime",
    "PacketWakeSupported",
    "PanelColor",
    "PanelGroup",
    "PanelHeight",
    "PanelId",
    "PanelLength",
    "PanelPositionX",
    "PanelPositionY",
    "PanelPositionZ",
    "PanelRotationX",
    "PanelRotationY",
    "PanelRotationZ",
    "PanelShape",
    "PanelSide",
    "PanelVisible",
    "PanelWidth",
    "Parent",
    "PendingConfigurationIds",
    "PendingSoftwareInstall",
    "PersistSystemGeneralize",
    "PhysicalDeviceLocation",
    "PhysicalDeviceLocationJoint",
    "PhysicalDeviceLocationPanel",
    "PhysicalDeviceLocationSpatial",
    "PostInstallInProgress",
    "PowerData",
    "PowerRelations",
    "PresenceNotForDevice",
    "PreventDriverLoad",
    "ProblemCode",
    "ProblemStatus",
    "ProblemStatusOverride",
    "RemoteUrls",
    "RemovalPolicy",
    "RemovalPolicyDefault",
    "RemovalPolicyOverride",
    "RemovalRelations",
    "Reported",
    "ReportedDeviceIdsHash",
    "RequestConfigurationIds",
    "ResourcePickerExceptions",
    "ResourcePickerTags",
    "RestrictedSD",
    "RollbackDriverNode",
    "SafeRemovalRequired",
    "SafeRemovalRequiredOverride",
    "Security",
    "SecuritySDS",
    "SendPacketWakeSupported",
    "Service",
    "SessionId",
    "ShowInUninstallUI",
    "Siblings",
    "SignalStrength",
    "SinkProtocolInfo",
    "SoftRestartSupported",
    "Stack",
    "StateDirectoryId",
    "SupportedUriSchemes",
    "SupportsAudio",
    "SupportsImages",
    "SupportsMute",
    "SupportsSearch",
    "SupportsSetNextAVT",
    "SupportsVideo",
    "TerminalLuid",
    "Text_Description",
    "TransportRelations",
    "UDN",
    "UINumber",
    "UINumberDescFormat",
    "UpdateWithUngroupedDrivers",
    "UpperFilters",
    "UserSelectedDriverInstalled",
}

DeviceClass = {
    "BootCritical",
    "Characteristics",
    "ClassCoInstallers",
    "ClassInstaller",
    "ClassName",
    "CompatibleFeatureScores",
    "CompoundLowerFilters",
    "CompoundUpperFilters",
    "ConfigFilters",
    "ConfigNotifyWnfTriggers",
    "Configurable",
    "ConfigurableClassVersion",
    "ConfigurableOverride",
    "ConfigureSchemaSettings",
    "DHPRebalanceOptOut",
    "DefaultService",
    "DevType",
    "Exclusive",
    "FSFilterClass",
    "Icon",
    "IconPath",
    "Inbox",
    "InstallWizardProvider",
    "LastDeleteDate",
    "LowerFilters",
    "LowerLogoVersion",
    "Name",
    "NeedsReinstall",
    "NoDisplayClass",
    "NoInstallClass",
    "NoUseClass",
    "OmitFromSystemSpec",
    "PolicyExempt",
    "PreConfigure",
    "Primitive",
    "PropPageProvider",
    "ReinstallApplicableDevices",
    "Security",
    "SecuritySDS",
    "SilentInstall",
    "SystemCritical",
    "TransactedInstall",
    "UpperFilters",
}

DeviceContainer = {
    "Address",
    "AlwaysShowDeviceAsConnected",
    "AssociationArray",
    "AutoPlay_AppUserModelID",
    "AutoPlay_ApplicationID",
    "AutoPlay_AutoplayType",
    "AutoPlay_ContainerAutoplay",
    "AutoPlay_Handler",
    "AutoPlay_PackageFamilyName",
    "AutoPlay_PackageName",
    "AutoPlay_PackagePublisher",
    "AutoPlay_RegisteredAppsEnabled",
    "AutoPlay_Verb",
    "BaselineExperienceId",
    "BatteryLevel",
    "BatteryLow",
    "Category",
    "CategoryGroup_Desc",
    "CategoryGroup_Icon",
    "Category_Desc_Plural",
    "Category_Desc_Singular",
    "Category_Icon",
    "ConfigFlags",
    "CustomPrivilegedPackageFamilyNames",
    "DCA_AppUserModelID",
    "DCA_ApplicationID",
    "DCA_DeviceNotificationHandlers",
    "DCA_ItemNameDisplay",
    "DCA_PackageFamilyName",
    "DCA_PackageName",
    "DCA_PackagePublisher",
    "DCA_Tile_Background",
    "DCA_Tile_KeystoneImagePath",
    "DCA_WnfStateName",
    "DeviceDescription1",
    "DeviceDescription2",
    "DeviceFunctionSubRank",
    "DiscoveryMethod",
    "ExperienceId",
    "FriendlyName",
    "GlyphIconPath",
    "GlyphId",
    "HasProblem",
    "Icon",
    "InstallInProgress",
    "IsAuthenticated",
    "IsConnected",
    "IsDefaultDevice",
    "IsDeviceUniquelyIdentifiable",
    "IsEncrypted",
    "IsLocalMachine",
    "IsMetadataSearchInProgress",
    "IsNetworkDevice",
    "IsNotInterestingForDisplay",
    "IsPaired",
    "IsRebootRequired",
    "IsSharedDevice",
    "IsShowInDisconnectedState",
    "Last_Connected",
    "Last_Seen",
    "LaunchDeviceStageFromExplorer",
    "LaunchDeviceStageOnDeviceConnect",
    "Manufacturer",
    "MetadataCabinet",
    "MetadataChecksum",
    "MetadataPath",
    "ModelName",
    "ModelNumber",
    "PrimaryCategory",
    "PrivilegedPackageFamilyNames",
    "RequiresPairingElevation",
    "RequiresUninstallElevation",
    "UnpairUninstall",
    "Version",
    "WindowsHardwareLogoCertified",
}

DeviceDisplay = {
    "UserLastAccessTime",
}

DeviceId = {
    "DriverInfMatches",
    "DriverInfNames",
}

DeviceInterface = {
    "AutoPlay_CustomEventGuid",
    "Autoplay_Silent",
    "ClassGuid",
    "ClassGuidForPolicy",
    "Enabled",
    "FriendlyName",
    "HID_BackgroundAccess",
    "HID_IsReadOnly",
    "HID_ProductId",
    "HID_UsageId",
    "HID_UsagePage",
    "HID_VendorId",
    "HID_VersionNumber",
    "ReferenceString",
    "Restricted",
    "SchematicName",
    "Serial_PortName",
    "Serial_UsbProductId",
    "Serial_UsbVendorId",
    "UnrestrictedAppCapabilities",
}

DeviceInterfaceClass = {
    "DefaultInterface",
    "Inbox",
    "Name",
    "UnrestrictedAppCapabilities",
}

DeviceItem = {
    "SetupProgress",
    "State",
    "Status",
}

DeviceItemParam = {
    "AsyncItemInitDelaysEnumComplete",
}

DevicePanel = {
    "AdjacentPanels",
    "Color",
    "ContainerId",
    "Group",
    "Height",
    "JointDetachable",
    "JointPanels",
    "JointPositionCurrent",
    "JointPositionDefault",
    "JointPositionMax",
    "JointPositionMin",
    "JointRotationCurrent",
    "JointRotationDefault",
    "JointRotationMax",
    "JointRotationMin",
    "JointSourcePanelEdge",
    "JointTargetPanelEdge",
    "JointTargetPanelId",
    "JointTargetPositionX",
    "JointTargetPositionY",
    "JointTargetPositionZ",
    "JointTargetRotationX",
    "JointTargetRotationY",
    "JointTargetRotationZ",
    "JointType",
    "Side",
    "Width",
}

DeviceSetup = {
    "AutoplayReady",
    "AutoplayState",
    "ConnectivityNeeded",
    "CostedNetworkPolicyExempt",
    "DCA_State",
    "DeviceState",
    "DriverState",
    "FirstInstallDate",
    "HSA_AvailableCompanionApps",
    "HSA_AvailableCompatibleApps",
    "HSA_AvailableEnhancerApps",
    "HSA_State",
    "HardErrorCount",
    "InstallDate",
    "InstallInProgress",
    "MetadataPackageId",
    "PairedAutomatically",
    "UXReady",
    "UserRefreshDate",
}

DriverDatabase = {
    "AccessMask",
    "ConfigMode",
    "ConfigOptions",
    "Disabled",
    "FilePath",
    "LastUpdateDate",
    "LoadStatus",
    "Loaded",
    "NodeName",
    "OemDriverInfFileMap",
    "ProcessorArchitecture",
    "RegistryPath",
    "SchemaVersion",
    "Selected",
    "SetupOptions",
    "SetupStatus",
    "SystemRoot",
    "UnloadTimeout",
    "Updated",
    "Version",
}

DriverFile = {
    "DriverInfName",
    "Owners",
    "ProtectionClass",
    "SubDirectory",
}

DriverInfFile = {
    "ActiveConfigurations",
    "ActiveDriverPackage",
    "DriverPackages",
    "Locked",
}

DriverPackage = {
    "BootCritical",
    "CatalogFile",
    "ClassGuid",
    "ClassVersion",
    "Configurable",
    "ConfigurableFlags",
    "ConfigurableOverride",
    "ConfigurationScopes",
    "Configurations",
    "DriverDate",
    "DriverFlightIds",
    "DriverInfName",
    "DriverPackageId",
    "DriverRecoveryIds",
    "DriverSetIds",
    "DriverUpdateIds",
    "DriverVersion",
    "EffectiveFileSize",
    "ExtensionContractIds",
    "ExtensionId",
    "F6",
    "FamilyId",
    "FileSize",
    "FirmwareDependencies",
    "FirmwareDependencyBootSession",
    "GroupIds",
    "ImportDate",
    "Inbox",
    "Locale",
    "LockLevel",
    "NeedsReconfig",
    "OriginalInfName",
    "PendingDriverUpdate",
    "ProcessorArchitecture",
    "ProductName",
    "ProviderName",
    "Published",
    "RelatedDriverPackages",
    "SignerName",
    "SignerScore",
    "SourceMediaPath",
    "StatusFlags",
    "SubmissionId",
    "SystemCritical",
    "TargetComputerIds",
    "UpdateAttempts",
}

DriverRegKey = {
    "KeyOnly",
    "Owners",
}

DriverService = {
    "BootFlags",
    "Description",
    "DisplayName",
    "ErrorControl",
    "Group",
    "GroupDependencies",
    "ImagePath",
    "ObjectName",
    "Owners",
    "ServiceDependencies",
    "StartType",
    "Tag",
    "Type",
}

DrvPkg = {
    "BrandingIcon",
    "DetailedDescription",
    "DocumentationLink",
    "Icon",
    "Model",
    "VendorWebSite",
}

FirmwareResource = {
    "Id",
    "LastAttemptDate",
    "LastAttemptStatus",
    "LastAttemptVersion",
    "LowestSupportedVersion",
    "PendingVersion",
    "Type",
    "Version",
}

HdAudBus = {
    "DisableNonSnoop",
    "ForcedCacheType",
}

IPP = {
    "LocalNetwork",
    "LocationListQuery",
    "LocationListResponse",
    "PrinterKeywordFilter",
    "PrinterLimit",
    "PrinterLocationFilter",
    "PrinterMakeAndModel",
    "PrinterOffset",
    "PrinterOrgLocation",
    "PrinterSortBy",
    "PrinterTotalCount",
}

Imaging = {
    "Port",
}

InfraCast = {
    "AccessPointBssid",
    "ChallengeAep",
    "DevnodeAep",
    "HostName_ResolutionMode",
    "PinSupported",
    "SinkHostName",
    "SinkIpAddress",
    "StreamSecuritySupported",
    "Supported",
}

IoT = {
    "AllJoynSoftwareVersion",
    "AppId",
    "AppName",
    "AppSoftwareVersion",
    "BusName",
    "CustomCategory",
    "DefaultLang",
    "HardwareVersion",
    "ServiceInterfaces",
    "SessionPort",
}

KsAudio = {
    "Controller_DeviceInterface_Path",
    "PacketSize_Constraints",
    "PacketSize_Constraints2",
}

KsMidiPort = {
    "KsFilterInterfaceId",
    "KsPinId",
}

MTPBTH = {
    "IsConnected_Private",
}

Mbae = {
    "NetworkAccountId",
    "NetworkInterfaceId",
}

Midi = {
    "Device_Tag",
}

NFP = {
    "Capabilities",
}

PUBSVCS = {
    "METADATA",
}

PciDevice = {
    "AERCapabilityPresent",
    "AcsCapabilityRegister",
    "AcsCompatibleUpHierarchy",
    "AcsSupport",
    "AriSupport",
    "AtomicsSupported",
    "AtsSupport",
    "BarTypes",
    "BaseClass",
    "Correctable_Error_Mask",
    "CurrentLinkSpeed",
    "CurrentLinkWidth",
    "CurrentPayloadSize",
    "CurrentSpeedAndMode",
    "DeviceType",
    "ECRC_Errors",
    "Error_Reporting",
    "ExpressSpecVersion",
    "FirmwareErrorHandling",
    "InterruptMessageMaximum",
    "InterruptSupport",
    "Label_Id",
    "Label_String",
    "MaxLinkSpeed",
    "MaxLinkWidth",
    "MaxPayloadSize",
    "MaxReadRequestSize",
    "ProgIf",
    "RequiresReservedMemoryRegion",
    "RootError_Reporting",
    "S0WakeupSupported",
    "SriovSupport",
    "SubClass",
    "Uncorrectable_Error_Mask",
    "Uncorrectable_Error_Severity",
}

PciRootBus = {
    "ASPMSupport",
    "ClockPowerManagementSupport",
    "CurrentSpeedAndMode",
    "DeviceIDMessagingCapable",
    "ExtendedConfigAvailable",
    "ExtendedPCIConfigOpRegionSupport",
    "MSISupport",
    "NativePciExpressControl",
    "PCIExpressAERControl",
    "PCIExpressCapabilityControl",
    "PCIExpressNativeHotPlugControl",
    "PCIExpressNativePMEControl",
    "PCISegmentGroupsSupport",
    "SHPCNativeHotPlugControl",
    "SecondaryBusWidth",
    "SecondaryInterface",
    "SupportedSpeedsAndModes",
    "SystemMsiSupport",
}

Pos = {
    "ConnectionTypes",
    "DeviceConnectionString",
    "IsCustomPairing",
    "PosDeviceTypes",
    "ProtocolProviderDllName",
    "ProviderId",
    "SetPairingState",
    "VideoPreviewSupport",
}

Radio = {
    "ManagerCLSID",
    "Signature",
}

SSDP = {
    "AltLocationInfo",
    "DevLifeTime",
    "NetworkLocationInfo",
}

Smartcard = {
    "DeviceReady",
    "FileSystem",
    "Friendly",
    "MachineId",
    "Transport",
    "VCard",
}

Storage = {
    "Disk_Number",
    "Gpt_Name",
    "Gpt_Type",
    "Mbr_Type",
    "Partition_Number",
    "Portable",
    "Removable_Media",
    "System_Critical",
}

TSUSB = {
    "BUS_ENUMERATOR_TAG",
}

UPNP = {
    "AepServiceList",
    "FoundOnPublicNetwork",
    "IsDialDevice",
    "IsNetworkInterfacePublic",
    "WiFiDirectMacAddress",
}

User = {
    "Provided_Name",
}

WIA = {
    "DeviceType",
}

WSD = {
    "AepServiceList",
    "AppSeqInstanceID",
    "Challenge_Query",
    "Convert_To_Multicast",
    "DisableIPPAssociation",
    "FoundOnPublicNetwork",
    "Hello_Result",
    "IPConnectionString",
    "MetadataUpdated",
    "PreferredIPAddressFamily",
    "ResurrectedOfflineDevice",
    "Supports_DNS",
    "WiFiDirectMacAddress",
}

WiFi = {
    "InterfaceGuid",
}

WiFiDirect = {
    "AutoConnect",
    "DeviceAddress",
    "DeviceAddressCopy",
    "FoundWsbService",
    "GroupId",
    "InformationElements",
    "InterfaceAddress",
    "InterfaceGuid",
    "IsConnected",
    "IsDMGCapable",
    "IsLegacyDevice",
    "IsMiracastLCPSupported",
    "IsRecentlyAssociated",
    "IsVisible",
    "LinkQuality",
    "MiracastVersion",
    "NoMiracastAutoProject",
    "ProfileString",
    "Service_Aeps",
    "Services",
    "SupportedChannelList",
    "TransientAssociation",
}

WiFiDirectParam = {
    "CachedDiscovery",
    "DisableMiracastAutoProject",
    "DiscoverWSBDocks",
    "EnableAggressiveDiscovery",
    "EnableFirewallPreconfiguration",
    "EnableMultipleInterfaceDiscovery",
    "ServiceIdPrefix",
    "ServiceInfoDiscovery",
}

WiFiDirectServices = {
    "AdvertisementId",
    "RequestServiceInformation",
    "ServiceAddress",
    "ServiceConfigMethods",
    "ServiceInformation",
    "ServiceName",
}

Winusb = {
    "Device_Class",
    "Device_Custom_Interface_GUIDs",
    "Device_PID",
    "Device_Protocol",
    "Device_SubClass",
    "Device_VID",
}

WpdFs = {
    "VolumePath",
}

DEVPKEY_LIST = (
    # special groups
    ("Device", Device),
    ("DeviceContainer", DeviceContainer),
    ("FirmwareResource", FirmwareResource),
    ("PciDevice", PciDevice),
    ("PciRootBus", PciRootBus),
    # other groups
    ("Aep", Aep),
    ("AepContainer", AepContainer),
    ("AepService", AepService),
    ("Bluetooth", Bluetooth),
    ("BluetoothLE", BluetoothLE),
    ("DasParam", DasParam),
    ("DevQuery", DevQuery),
    # ("Device", Device),
    ("DeviceClass", DeviceClass),
    # ("DeviceContainer", DeviceContainer),
    ("DeviceDisplay", DeviceDisplay),
    ("DeviceId", DeviceId),
    ("DeviceInterface", DeviceInterface),
    ("DeviceInterfaceClass", DeviceInterfaceClass),
    ("DeviceItem", DeviceItem),
    ("DeviceItemParam", DeviceItemParam),
    ("DevicePanel", DevicePanel),
    ("DeviceSetup", DeviceSetup),
    ("DriverDatabase", DriverDatabase),
    ("DriverFile", DriverFile),
    ("DriverInfFile", DriverInfFile),
    ("DriverPackage", DriverPackage),
    ("DriverRegKey", DriverRegKey),
    ("DriverService", DriverService),
    ("DrvPkg", DrvPkg),
    # ("FirmwareResource", FirmwareResource),
    ("HdAudBus", HdAudBus),
    ("IPP", IPP),
    ("Imaging", Imaging),
    ("InfraCast", InfraCast),
    ("IoT", IoT),
    ("KsAudio", KsAudio),
    ("KsMidiPort", KsMidiPort),
    ("MTPBTH", MTPBTH),
    ("Mbae", Mbae),
    ("Midi", Midi),
    ("NFP", NFP),
    ("PUBSVCS", PUBSVCS),
    # ("PciDevice", PciDevice),
    # ("PciRootBus", PciRootBus),
    ("Pos", Pos),
    ("Radio", Radio),
    ("SSDP", SSDP),
    ("Smartcard", Smartcard),
    ("Storage", Storage),
    ("TSUSB", TSUSB),
    ("UPNP", UPNP),
    ("User", User),
    ("WIA", WIA),
    ("WSD", WSD),
    ("WiFi", WiFi),
    ("WiFiDirect", WiFiDirect),
    ("WiFiDirectParam", WiFiDirectParam),
    ("WiFiDirectServices", WiFiDirectServices),
    ("Winusb", Winusb),
    ("WpdFs", WpdFs),
)
