
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-06T17:04:06-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "42d821bfdd09a897fa8f94be6b87e41760e29cfc",
 "version": "0.13.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
