# Generated by Django 2.2.3 on 2019-09-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("meta_subject", "0005_auto_20190903_2018")]

    operations = [
        migrations.RenameField(
            model_name="bloodresultsglu", old_name="blood_glucose", new_name="glucose"
        ),
        migrations.RenameField(
            model_name="bloodresultsglu",
            old_name="blood_glucose_abnormal",
            new_name="glucose_abnormal",
        ),
        migrations.RenameField(
            model_name="bloodresultsglu",
            old_name="blood_glucose_reportable",
            new_name="glucose_reportable",
        ),
        migrations.RenameField(
            model_name="bloodresultsglu",
            old_name="blood_glucose_units",
            new_name="glucose_units",
        ),
        migrations.RenameField(
            model_name="historicalbloodresultsglu",
            old_name="blood_glucose",
            new_name="glucose",
        ),
        migrations.RenameField(
            model_name="historicalbloodresultsglu",
            old_name="blood_glucose_abnormal",
            new_name="glucose_abnormal",
        ),
        migrations.RenameField(
            model_name="historicalbloodresultsglu",
            old_name="blood_glucose_reportable",
            new_name="glucose_reportable",
        ),
        migrations.RenameField(
            model_name="historicalbloodresultsglu",
            old_name="blood_glucose_units",
            new_name="glucose_units",
        ),
    ]
