# Generated by Django 2.2.3 on 2019-09-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("meta_subject", "0006_auto_20190910_1702")]

    operations = [
        migrations.RenameField(
            model_name="bloodresultsglu",
            old_name="blood_glucose_assay_datetime",
            new_name="glucose_assay_datetime",
        ),
        migrations.RenameField(
            model_name="bloodresultsglu",
            old_name="blood_glucose_requisition",
            new_name="glucose_requisition",
        ),
        migrations.RenameField(
            model_name="historicalbloodresultsglu",
            old_name="blood_glucose_assay_datetime",
            new_name="glucose_assay_datetime",
        ),
        migrations.RenameField(
            model_name="historicalbloodresultsglu",
            old_name="blood_glucose_requisition",
            new_name="glucose_requisition",
        ),
    ]
