
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-15T17:06:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f82551414e66d25793ac8697915ab8a0f5f96e30",
 "version": "1.0.0rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
