# Generated by Django 2.2.3 on 2019-08-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources_tracking', '0004_auto_20180418_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'tsv'), (1, 'csv'), (2, 'txt'), (3, 'json'), (4, 'html'), (5, 'fastq'), (6, 'bam'), (7, 'cram'), (8, 'gvcf'), (9, 'vcf'), (10, 'report'), (11, 'bed'), (12, 'bigwig'), (13, 'wigfix'), (14, 'chromatograms'), (15, 'other'), (16, 'bam_index'), (17, 'vcf_index'), (18, 'fasta'), (19, 'fasta_index'), (20, 'fasta_dict'), (21, 'executable'), (22, 'tabix_index'), (23, 'xls'), (24, 'xlsx')]),
        ),
    ]
