[tool.poetry]
name = "djangorestcli"
version = "0.1.1"
description = ""
authors = ["Ronnasayd Machado <ronnasayd@hotmail.com>"]

[tool.poetry.dependencies]
python = "^2.7 || 3.6"
argparse = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
