name: pudl-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8            # dev
  - bandit              # dev
  - coloredlogs         # base
  - coverage            # dev
  - dask                # user
  - datapackage>=1.9.0  # base We depend on features introduced in v1.9.0
  - dbfread             # base
  - doc8                # dev
  - flake8              # dev
  - flake8-colors       # dev
  - flake8-docstrings   # dev
  - flake8-builtins     # dev
  - goodtables          # base
  - ipdb                # dev
  - isort               # dev
  - jedi                # dev
  - jupyter             # user
  - jupyterlab          # user
  - matplotlib          # base
  - nbval               # dev
  - networkx>=2.2       # base We depend on features introduced in v2.2
  - numpy               # base
  - pandas>=0.24        # base We depend on features introduced in 0.24
  - pandoc              # dev
  - pdbpp               # dev
  - pep8-naming         # dev
  - pip                 # N/A
  - pre_commit          # dev
  - pyarrow>=0.14.0     # base compilation issues below 0.14.0
  - pydocstyle          # dev
  - pytest              # dev
  - pytest-cov          # dev
  - python>=3.7         # N/A
  - python-snappy       # base
  - pyyaml              # base
  - scikit-learn>=0.20  # base pandas integration added in v0.20
  - scipy               # base
  - setuptools_scm      # dev
  - sphinx              # dev
  - sphinx_rtd_theme    # dev
  - sqlalchemy>=1.3.0   # base Security issues below v1.3.0
  - tableschema         # base
  - tableschema-sql     # base
  - timezonefinder      # base
  - tox                 # dev
  - twine               # dev
  - xlsxwriter          # base
