[tool.poetry]
name = "simple_test_process"
version = "0.5.0"
description = "The process ran by simple_test to isolate the environment"
authors = ["Philip Olson <philip.olson@pm.me>"]
license = "WTFNMFPL-1.0"
readme = "README.md"
repository = "https://github.com/olsonpm/py_simple-test-process"
include = [
  "simple_test_process/license.txt",
  "simple_test_process/top_level.txt",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
toml = "^0.10.0"
is_git_repo_clean = "^0.3.4"
rm = "^2018.11"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
simple_chalk = "^0.1.0"
num2words = "^0.5.10"
"po.case_conversion" = "0.2.0"

[tool.vendorize]
target = "simple_test_process/_vendor"
packages = [
  "toml >=0.10.0,<0.11",
  "po.case_conversion==0.2.0",
  "wrapt >=1.10,<1.11",
  "ordered_set >=3.1,<3.2",
  "tedent >=0.1.5,<0.2",
  "simple_test_default_reporter >=0.2.0,<0.3",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
