#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

extras_require = \
{'test': ['pytest', 'pytest-cov', 'tox']}

setup(name='spooner',
      version='0.2',
      description='spooner',
      author='Danny McVey',
      author_email='',
      url='https://github.com/danmaps/spooner',
      py_modules=['spooner'],
      extras_require=extras_require,
     )
