# coding: utf-8

"""
    Budgea API Documentation

    see https://www.budget-insight.com/budgea-api  # noqa: E501

    OpenAPI spec version: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import budgea
from budgea.models.hash_table import HashTable  # noqa: E501
from budgea.rest import ApiException


class TestHashTable(unittest.TestCase):
    """HashTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHashTable(self):
        """Test HashTable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = budgea.models.hash_table.HashTable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
