dist: xenial
sudo: false
language: python

jobs:
  include:
    - stage: test
      python: 2.7
      env: TOXENV=py27
    - stage: test-pandas
      python: 2.7
      env: TOXENV=py27-pandas
    - stage: test
      python: 3.4
      env: TOXENV=py34
    - stage: test
      python: 3.5
      env: TOXENV=py35
    - stage: test-pandas
      python: 3.5
      env: TOXENV=py35-pandas
    - stage: test
      python: 3.6
      env: TOXENV=py36
    - stage: test-pandas
      python: 3.6
      env: TOXENV=py36-pandas
    - stage: test
      python: 3.7
      env: TOXENV=py37
    - stage: test-pandas
      python: 3.7
      env: TOXENV=py37-pandas
    - stage: deploy
      if: tag IS present
      python: *latest_py3
      install: skip
      script: skip
      deploy:
        provider: pypi
        on:
          tags: true
          all_branches: true
        user: __token__
        password:
          secure: pypi-AgEIcHlwaS5vcmcCJDMwZjY3Y2ZmLWE4YzYtNGI4Ni05NDU4LTgzNDAyMzRhMGZjYgACOHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJzY3J1bmNoIl19LCAidmVyc2lvbiI6IDF9AAAGIPgz--kOdedlCrCnOtjH40TsDvKxZbTWl4Bu8cjM5mXs
        distributions: dists
        skip_cleanup: true
        skip_upload_docs: true

cache: pip

install:
- pip install tox

script:
  - tox
