[tool.poetry]
name = "swashbookler"
version = "1.0.1"
description = "Allows downloading books from Google Books and converting them to PDFs."
authors = ["Coriander Pines"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
bs4 = "^0.0.1"
requests = "^2.22"
pillow = "^6.1"
img2pdf = "^0.3.3"
PyYAML = "^5.1"
click = "^7.0"

[tool.poetry.dev-dependencies]
mypy = "^0.720.0"

[tool.poetry.scripts]
swashbookler = 'swashbookler.cli:cli'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

