DROP TABLE IF EXISTS tfidf;
DROP TABLE IF EXISTS documentInfo;


CREATE TABLE tfidf (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  terms TEXT UNIQUE NOT NULL,
  wordFreqValue TEXT NOT NULL
);


CREATE TABLE documentInfo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id INTEGER NOT NULL,
  wordcount INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Doctitle TEXT NOT NULL,
  Docbody TEXT NOT NULL,
  FOREIGN KEY (document_id) REFERENCES tfidf (id)
);
