# Generated by Django 2.2.4 on 2019-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('polls', '0002_auto_20190830_0657'), ('polls', '0003_auto_20190830_0658')]

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
    ]
