
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-15T23:56:11-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "44741169a8c6ab5506db4975b15100ee95849bd3",
 "version": "0+untagged.520.g4474116.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
