sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
cache:
    directories:
        - ${HOME}/.cache/pip
install:
  - pip install -U setuptools pip
  - pip install .
script: python example/example.py --local
