- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - check-requirements
    gate:
      queue: kuryr
