dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: 0CZ+qfOF9R7Ftny7oarpRw7RkA3dMHiy1SCFeFV9jAYf9OM1rxNMK2jOZD2A0oLUvNeBG69sfY2spWcryCMZYPCz5U+ZZaS0srvVu4M9ZQNX5LLCiYncxlhAt0x03X3L80ok+M9+pjPzC9JlWc+Fk+kvyhF/WEh/J3GOCuj91LJ2IpXCdoUWkUm8uLE5JsHOZJUg9kT37XmUgx6v9Ld7s7wpFn3jDFdBccL9bMF+Qu/gj7NLBKRmpGVo2sJNziXwSimUCijbRAgI/o+lBbf1WDs6PnXC8jkmYgyT5m2wxkYSiPecrXut2wVKlncfFmSsYTdp6Uwi3ZWViW22wID4c0OKZgsPwNgIvuBkBQAEz+DEsxmBysOGgPLG5dW8ZqCJrTU89FkgwQxX0RR3/oQB3AIeNhaBqzRX4PwskcdzA5x0V636xd5W7qsqgfvGbMfHweHMao5ZL0OtWduvfp3KupoLeBWd/ruRne0dnNNlpy+oLeomdCvtqUPeA1z1zmhJOYZb87tfa0wlpOH8n5iw59KOXYJSSvFA5+Zly432Yd2bXpARedviFOeqbBSSxgd0HVDXrS5Ik7pbxgZBQsW9os6U7TqWSghi2mI5ubiqMUWB2pBLLZAXweWcUu8aSmUHzbnebSbMB9qruDytk3sX94brrRDzPurZen1P99h+Tlo=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_bme680.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-bme680 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
