[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
dist-name = "hadrian-proxy"
module = "hadrian"
author = "schen"
author-email = "shu@disinformationindex.org"
home-page = "https://bitbucket.org/disinformationindex/hadrian/src"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = [
	"tornado >=6.0.3",
]
requires-python = ">=3.6"
