from enum import Enum

class Concept(Enum):
    AIRLINE_TICKET_PURCHASE = "AIRLINE_TICKET_PURCHASE"
    AIRLINE_ANCILIARIES_SERVICE_PURCHASE = "AIRLINE_ANCILIARIES_SERVICE_PURCHASE"
    REFUND = "REFUND"
    TRANSFER_ACCREDITATION = "TRANSFER_ACCREDITATION"
    CONDITIONAL_DISCOUNT = "CONDITIONAL_DISCOUNT"
