# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-09-11T15:32:18.182022'

__version__ = '2019.9'
__sha__ = '4ba76f005ae5731a190214bd5b8f1217eb666c59'
__revision__ = '4ba76f005ae5731a190214bd5b8f1217eb666c59'
