- src: https://github.com/mixbytes/tank.ansible-core
  version: master
  name: tank.ansible-core

- src: https://github.com/geerlingguy/ansible-role-docker
  version: master
  name: tank.docker

- src: https://github.com/mixbytes/tank.ansible-promstack
  version: master
  name: mixbytes.promstack
