sudo: true
dist: xenial
sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      export PATH=/home/travis/miniconda2/bin:$PATH;
    else
      export PATH=/home/travis/miniconda3/bin:$PATH;
    fi
  - conda update --yes conda
  - sudo apt-get update
  - sudo apt-get install libc6
  - conda install --yes libgcc
  - sudo apt-get install python-dev
  - sudo apt-get install python3-dev
install:
  - conda create --yes -n shorttext-test python=$TRAVIS_PYTHON_VERSION
  - source activate shorttext-test
  - pip install Cython
  - pip install -U numpy
  - pip install -U scipy
  - pip install google-compute-engine
  - pip install -U tensorflow
  - pip install -U .
  - python -m spacy download en
script:
  - python setup.py test

# Anaconda running in CI
#   https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html