[tool.poetry]
name = "pivotal_parser"
version = "0.1.0"
description = "Tool to parse out Pivotal Tracker CSVs."
authors = ["Adam Drewery <adam@verypossible.com>"]

[tool.poetry.scripts]
pivotal_parser = 'pivotal_parser:cli.run'

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0.25.1"
click = "^7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
