# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 2.3.33.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataDriftQueryDto(Model):
    """DataDriftQueryDto.

    :param model_name:
    :type model_name: str
    :param model_version:
    :type model_version: int
    :param services:
    :type services: list[str]
    """

    _attribute_map = {
        'model_name': {'key': 'modelName', 'type': 'str'},
        'model_version': {'key': 'modelVersion', 'type': 'int'},
        'services': {'key': 'services', 'type': '[str]'},
    }

    def __init__(self, model_name=None, model_version=None, services=None):
        super(DataDriftQueryDto, self).__init__()
        self.model_name = model_name
        self.model_version = model_version
        self.services = services
