[tool.poetry]
name = "class-doc"
version = "0.1.0"
description = "Extract attributes docstrings defined in various ways"
authors = ["Daniel Daniels <danields761@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
more-itertools = "^7.2"

[tool.poetry.dev-dependencies]
pytest = "^5.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
skip_string_normalization = true
exclude = "test_class_doc.py"
