parameters:
  whl:
    baseDir: 'dbfs:/FileStore/jars'

services:
  DbxDeploy.Logger.StreamLoggerFactory:

  DbxDeploy.Cluster.ClusterRestarter:
    arguments:
      - '%databricks.clusterId%'

  logging.Logger:
    class: logging.Logger
    factory: ['@DbxDeploy.Logger.StreamLoggerFactory', 'create']
    arguments:
      - 'deploy'

  DbxDeploy.Deployer:
    arguments:
      - '%databricks.projectBasePath%'

  DbxDeploy.DeployerJobSubmitter:
    arguments:
      - '%databricks.projectBasePath%'

  DbxDeploy.DeployWithCleanup:
    arguments:
      - '%databricks.projectBasePath%'

  DbxDeploy.Setup.SetupLoader:

  DbxDeploy.Setup.SetupBuilder:

  DbxDeploy.Whl.WhlUploader:
    arguments:
      - '%whl.baseDir%'

  DbxDeploy.Whl.WhlDeployer:
    arguments:
      - '%databricks.projectBasePath%'

  DbxDeploy.Dbc.DbcCreator:
    arguments:
      - '%whl.baseDir%'

  DbxDeploy.Dbc.DbcUploader:
    arguments:
      - '%databricks.projectRoot%'

  DbxDeploy.Dbc.PathsPreparer:

  DbxDeploy.Dbc.DbcDeployer:
    arguments:
      - '%databricks.projectBasePath%'

  DbxNotebookExporter.Json.JsonNotebookExporter:

  DbxDeploy.Job.JobsDeleter:

  DbxDeploy.Job.JobCreator:
    arguments:
      - '%databricks.clusterId%'
      - '%databricks.projectRoot%'

  DbxDeploy.Job.JobsCreatorAndRunner:

  DbxDeploy.Job.JobSubmitter:
    arguments:
      - '%databricks.clusterId%'
      - '%databricks.projectRoot%'
      - '%browser%'

  DbxDeploy.Job.RunsGetter:
    arguments:
      - '%databricks.clusterId%'
      - '%databricks.projectRoot%'

  DbxDeploy.Job.NotebookKiller:

  databricks_api.databricks.DatabricksAPI:
    autowire: False
    arguments:
      -
        user: '%databricks.user%'
        host: '%databricks.host%'
        token: '%databricks.token%'
