[tool.poetry]
name = "hypothesis-typed"
version = "1.0.0"
description = "An alias for hypothesis-auto"
authors = ["Timothy Crosley <timothy.crosley@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
hypothesis_auto = "^1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.portray]
modules = ["hypothesis_auto"]

[tool.portray.mkdocs.theme]
favicon = "art/logo.png"
logo = "art/logo.png"
name = "material"
palette = {primary = "teal", accent = "cyan"}
