# Generated by Django 2.2.4 on 2019-08-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('oms_gallery', '0002_auto_20190714_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('abstractlang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='languages.AbstractLang')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Под заголовок')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oms_gallery.Gallery', verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Инфо блок',
                'verbose_name_plural': 'Инфо блок',
            },
            bases=('languages.abstractlang',),
        ),
    ]
